/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "state_machine_synth.v:1" *)
module state_machine_synth(clk, reset, init, umbral_MFs, umbral_VCs, umbral_Ds, empty_main_fifo, empty_fifo_VC0, empty_fifo_VC1, empty_fifo_D0, empty_fifo_D1, error_main, error_VC0, error_VC1, error_D0, error_D1, error_out, next_error, active_out, next_active, idle_out, next_idle, present_state, next_state, umbral_MFs_out, umbral_VCs_out, umbral_Ds_out, next_umbral_MFs, next_umbral_VCs, next_umbral_Ds);
  (* src = "state_machine_synth.v:46" *)
  wire _000_;
  (* src = "state_machine_synth.v:46" *)
  wire _001_;
  (* src = "state_machine_synth.v:46" *)
  wire _002_;
  (* src = "state_machine_synth.v:46" *)
  wire [3:0] _003_;
  (* src = "state_machine_synth.v:46" *)
  wire [3:0] _004_;
  (* src = "state_machine_synth.v:46" *)
  wire [3:0] _005_;
  (* src = "state_machine_synth.v:46" *)
  wire [3:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  (* src = "state_machine_synth.v:36" *)
  wire [4:0] FIFO_empties;
  (* src = "state_machine_synth.v:37" *)
  wire [4:0] FIFO_errors;
  (* src = "state_machine_synth.v:20" *)
  output active_out;
  (* src = "state_machine_synth.v:2" *)
  input clk;
  (* src = "state_machine_synth.v:11" *)
  input empty_fifo_D0;
  (* src = "state_machine_synth.v:12" *)
  input empty_fifo_D1;
  (* src = "state_machine_synth.v:9" *)
  input empty_fifo_VC0;
  (* src = "state_machine_synth.v:10" *)
  input empty_fifo_VC1;
  (* src = "state_machine_synth.v:8" *)
  input empty_main_fifo;
  (* src = "state_machine_synth.v:16" *)
  input error_D0;
  (* src = "state_machine_synth.v:17" *)
  input error_D1;
  (* src = "state_machine_synth.v:14" *)
  input error_VC0;
  (* src = "state_machine_synth.v:15" *)
  input error_VC1;
  (* src = "state_machine_synth.v:13" *)
  input error_main;
  (* src = "state_machine_synth.v:18" *)
  output error_out;
  (* src = "state_machine_synth.v:22" *)
  output idle_out;
  (* src = "state_machine_synth.v:4" *)
  input init;
  (* src = "state_machine_synth.v:21" *)
  output next_active;
  (* src = "state_machine_synth.v:19" *)
  output next_error;
  (* src = "state_machine_synth.v:23" *)
  output next_idle;
  (* src = "state_machine_synth.v:25" *)
  output [3:0] next_state;
  (* src = "state_machine_synth.v:31" *)
  output [3:0] next_umbral_Ds;
  (* src = "state_machine_synth.v:29" *)
  output [3:0] next_umbral_MFs;
  (* src = "state_machine_synth.v:30" *)
  output [3:0] next_umbral_VCs;
  (* src = "state_machine_synth.v:24" *)
  output [3:0] present_state;
  (* src = "state_machine_synth.v:3" *)
  input reset;
  (* src = "state_machine_synth.v:7" *)
  input [3:0] umbral_Ds;
  (* src = "state_machine_synth.v:28" *)
  output [3:0] umbral_Ds_out;
  (* src = "state_machine_synth.v:5" *)
  input [3:0] umbral_MFs;
  (* src = "state_machine_synth.v:26" *)
  output [3:0] umbral_MFs_out;
  (* src = "state_machine_synth.v:6" *)
  input [3:0] umbral_VCs;
  (* src = "state_machine_synth.v:27" *)
  output [3:0] umbral_VCs_out;
  NOT _120_ (
    .A(present_state[2]),
    .Y(_102_)
  );
  NOT _121_ (
    .A(error_main),
    .Y(_103_)
  );
  NOT _122_ (
    .A(active_out),
    .Y(_104_)
  );
  NOT _123_ (
    .A(reset),
    .Y(_105_)
  );
  NOT _124_ (
    .A(umbral_Ds_out[0]),
    .Y(_106_)
  );
  NOT _125_ (
    .A(umbral_Ds[0]),
    .Y(_107_)
  );
  NOT _126_ (
    .A(umbral_Ds_out[1]),
    .Y(_108_)
  );
  NOT _127_ (
    .A(umbral_Ds[1]),
    .Y(_109_)
  );
  NOT _128_ (
    .A(umbral_Ds_out[2]),
    .Y(_110_)
  );
  NOT _129_ (
    .A(umbral_Ds[2]),
    .Y(_111_)
  );
  NOT _130_ (
    .A(umbral_Ds_out[3]),
    .Y(_112_)
  );
  NOT _131_ (
    .A(umbral_Ds[3]),
    .Y(_113_)
  );
  NOT _132_ (
    .A(umbral_VCs_out[0]),
    .Y(_114_)
  );
  NOT _133_ (
    .A(umbral_VCs[0]),
    .Y(_115_)
  );
  NOT _134_ (
    .A(umbral_VCs_out[1]),
    .Y(_116_)
  );
  NOT _135_ (
    .A(umbral_VCs[1]),
    .Y(_117_)
  );
  NOT _136_ (
    .A(umbral_VCs_out[2]),
    .Y(_118_)
  );
  NOT _137_ (
    .A(umbral_VCs[2]),
    .Y(_119_)
  );
  NOT _138_ (
    .A(umbral_VCs_out[3]),
    .Y(_007_)
  );
  NOT _139_ (
    .A(umbral_VCs[3]),
    .Y(_008_)
  );
  NOT _140_ (
    .A(umbral_MFs_out[0]),
    .Y(_009_)
  );
  NOT _141_ (
    .A(umbral_MFs[0]),
    .Y(_010_)
  );
  NOT _142_ (
    .A(umbral_MFs_out[1]),
    .Y(_011_)
  );
  NOT _143_ (
    .A(umbral_MFs[1]),
    .Y(_012_)
  );
  NOT _144_ (
    .A(umbral_MFs_out[2]),
    .Y(_013_)
  );
  NOT _145_ (
    .A(umbral_MFs[2]),
    .Y(_014_)
  );
  NOT _146_ (
    .A(umbral_MFs_out[3]),
    .Y(_015_)
  );
  NOT _147_ (
    .A(umbral_MFs[3]),
    .Y(_016_)
  );
  NOR _148_ (
    .A(present_state[2]),
    .B(present_state[3]),
    .Y(_017_)
  );
  NAND _149_ (
    .A(present_state[0]),
    .B(_017_),
    .Y(_018_)
  );
  NOR _150_ (
    .A(present_state[1]),
    .B(_018_),
    .Y(_019_)
  );
  NOR _151_ (
    .A(_105_),
    .B(init),
    .Y(_020_)
  );
  NAND _152_ (
    .A(reset),
    .B(_019_),
    .Y(_021_)
  );
  NOR _153_ (
    .A(init),
    .B(_021_),
    .Y(_022_)
  );
  NAND _154_ (
    .A(_019_),
    .B(_020_),
    .Y(_023_)
  );
  NOR _155_ (
    .A(_107_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _156_ (
    .A(_106_),
    .B(_022_),
    .Y(_025_)
  );
  NOR _157_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NOT _158_ (
    .A(_026_),
    .Y(next_umbral_Ds[0])
  );
  NOR _159_ (
    .A(_109_),
    .B(_023_),
    .Y(_027_)
  );
  NOR _160_ (
    .A(_108_),
    .B(_022_),
    .Y(_028_)
  );
  NOR _161_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOT _162_ (
    .A(_029_),
    .Y(next_umbral_Ds[1])
  );
  NOR _163_ (
    .A(_111_),
    .B(_023_),
    .Y(_030_)
  );
  NOR _164_ (
    .A(_110_),
    .B(_022_),
    .Y(_031_)
  );
  NOR _165_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NOT _166_ (
    .A(_032_),
    .Y(next_umbral_Ds[2])
  );
  NOR _167_ (
    .A(_113_),
    .B(_023_),
    .Y(_033_)
  );
  NOR _168_ (
    .A(_112_),
    .B(_022_),
    .Y(_034_)
  );
  NOR _169_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NOT _170_ (
    .A(_035_),
    .Y(next_umbral_Ds[3])
  );
  NOR _171_ (
    .A(_115_),
    .B(_023_),
    .Y(_036_)
  );
  NOR _172_ (
    .A(_114_),
    .B(_022_),
    .Y(_037_)
  );
  NOR _173_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOT _174_ (
    .A(_038_),
    .Y(next_umbral_VCs[0])
  );
  NOR _175_ (
    .A(_117_),
    .B(_023_),
    .Y(_039_)
  );
  NOR _176_ (
    .A(_116_),
    .B(_022_),
    .Y(_040_)
  );
  NOR _177_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOT _178_ (
    .A(_041_),
    .Y(next_umbral_VCs[1])
  );
  NOR _179_ (
    .A(_119_),
    .B(_023_),
    .Y(_042_)
  );
  NOR _180_ (
    .A(_118_),
    .B(_022_),
    .Y(_043_)
  );
  NOR _181_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _182_ (
    .A(_044_),
    .Y(next_umbral_VCs[2])
  );
  NOR _183_ (
    .A(_008_),
    .B(_023_),
    .Y(_045_)
  );
  NOR _184_ (
    .A(_007_),
    .B(_022_),
    .Y(_046_)
  );
  NOR _185_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NOT _186_ (
    .A(_047_),
    .Y(next_umbral_VCs[3])
  );
  NOR _187_ (
    .A(_010_),
    .B(_023_),
    .Y(_048_)
  );
  NOR _188_ (
    .A(_009_),
    .B(_022_),
    .Y(_049_)
  );
  NOR _189_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOT _190_ (
    .A(_050_),
    .Y(next_umbral_MFs[0])
  );
  NOR _191_ (
    .A(_012_),
    .B(_023_),
    .Y(_051_)
  );
  NOR _192_ (
    .A(_011_),
    .B(_022_),
    .Y(_052_)
  );
  NOR _193_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOT _194_ (
    .A(_053_),
    .Y(next_umbral_MFs[1])
  );
  NOR _195_ (
    .A(_014_),
    .B(_023_),
    .Y(_054_)
  );
  NOR _196_ (
    .A(_013_),
    .B(_022_),
    .Y(_055_)
  );
  NOR _197_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOT _198_ (
    .A(_056_),
    .Y(next_umbral_MFs[2])
  );
  NOR _199_ (
    .A(_016_),
    .B(_023_),
    .Y(_057_)
  );
  NOR _200_ (
    .A(_015_),
    .B(_022_),
    .Y(_058_)
  );
  NOR _201_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOT _202_ (
    .A(_059_),
    .Y(next_umbral_MFs[3])
  );
  NOR _203_ (
    .A(_105_),
    .B(_050_),
    .Y(_005_[0])
  );
  NOR _204_ (
    .A(_105_),
    .B(_053_),
    .Y(_005_[1])
  );
  NOR _205_ (
    .A(_105_),
    .B(_056_),
    .Y(_005_[2])
  );
  NOR _206_ (
    .A(_105_),
    .B(_059_),
    .Y(_005_[3])
  );
  NOR _207_ (
    .A(_105_),
    .B(_026_),
    .Y(_004_[0])
  );
  NOR _208_ (
    .A(_105_),
    .B(_029_),
    .Y(_004_[1])
  );
  NOR _209_ (
    .A(_105_),
    .B(_032_),
    .Y(_004_[2])
  );
  NOR _210_ (
    .A(_105_),
    .B(_035_),
    .Y(_004_[3])
  );
  NOR _211_ (
    .A(_105_),
    .B(_038_),
    .Y(_006_[0])
  );
  NOR _212_ (
    .A(_105_),
    .B(_041_),
    .Y(_006_[1])
  );
  NOR _213_ (
    .A(_105_),
    .B(_044_),
    .Y(_006_[2])
  );
  NOR _214_ (
    .A(_105_),
    .B(_047_),
    .Y(_006_[3])
  );
  NOR _215_ (
    .A(present_state[1]),
    .B(present_state[0]),
    .Y(_060_)
  );
  NOR _216_ (
    .A(_102_),
    .B(present_state[3]),
    .Y(_061_)
  );
  NAND _217_ (
    .A(present_state[2]),
    .B(_060_),
    .Y(_062_)
  );
  NOR _218_ (
    .A(present_state[3]),
    .B(_062_),
    .Y(_063_)
  );
  NAND _219_ (
    .A(_060_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _220_ (
    .A(error_D1),
    .B(error_D0),
    .Y(_065_)
  );
  NOT _221_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _222_ (
    .A(error_VC1),
    .B(error_VC0),
    .Y(_067_)
  );
  NAND _223_ (
    .A(_103_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _224_ (
    .A(_066_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _225_ (
    .A(_063_),
    .B(_069_),
    .Y(_070_)
  );
  NOT _226_ (
    .A(_070_),
    .Y(_071_)
  );
  NAND _227_ (
    .A(_104_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _228_ (
    .A(present_state[3]),
    .B(reset),
    .Y(_073_)
  );
  NOT _229_ (
    .A(_073_),
    .Y(_074_)
  );
  NAND _230_ (
    .A(_102_),
    .B(_060_),
    .Y(_075_)
  );
  NOT _231_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _232_ (
    .A(_073_),
    .B(_075_),
    .Y(_077_)
  );
  NAND _233_ (
    .A(_074_),
    .B(_076_),
    .Y(_078_)
  );
  NAND _234_ (
    .A(_072_),
    .B(_078_),
    .Y(_079_)
  );
  NOT _235_ (
    .A(_079_),
    .Y(next_active)
  );
  NOR _236_ (
    .A(_105_),
    .B(_079_),
    .Y(_000_)
  );
  NOR _237_ (
    .A(present_state[3]),
    .B(_075_),
    .Y(_080_)
  );
  NAND _238_ (
    .A(reset),
    .B(_080_),
    .Y(_081_)
  );
  NAND _239_ (
    .A(_023_),
    .B(_081_),
    .Y(next_state[0])
  );
  NAND _240_ (
    .A(present_state[1]),
    .B(_017_),
    .Y(_082_)
  );
  NOR _241_ (
    .A(present_state[0]),
    .B(_082_),
    .Y(_083_)
  );
  NOT _242_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND _243_ (
    .A(empty_fifo_D1),
    .B(empty_fifo_D0),
    .Y(_085_)
  );
  NAND _244_ (
    .A(empty_fifo_VC1),
    .B(empty_fifo_VC0),
    .Y(_086_)
  );
  NOT _245_ (
    .A(_086_),
    .Y(_087_)
  );
  NAND _246_ (
    .A(empty_main_fifo),
    .B(_087_),
    .Y(_088_)
  );
  NOR _247_ (
    .A(_085_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _248_ (
    .A(_083_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _249_ (
    .A(init),
    .B(_019_),
    .Y(_091_)
  );
  NAND _250_ (
    .A(_090_),
    .B(_091_),
    .Y(next_state[1])
  );
  NAND _251_ (
    .A(reset),
    .B(next_state[1]),
    .Y(_092_)
  );
  NOT _252_ (
    .A(_092_),
    .Y(_003_[1])
  );
  NAND _253_ (
    .A(reset),
    .B(_083_),
    .Y(_093_)
  );
  NOR _254_ (
    .A(_089_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _255_ (
    .A(_071_),
    .B(_094_),
    .Y(_095_)
  );
  NOT _256_ (
    .A(_095_),
    .Y(next_state[2])
  );
  NOR _257_ (
    .A(_105_),
    .B(_095_),
    .Y(_003_[2])
  );
  NOR _258_ (
    .A(_064_),
    .B(_069_),
    .Y(_096_)
  );
  NAND _259_ (
    .A(reset),
    .B(_096_),
    .Y(_097_)
  );
  NAND _260_ (
    .A(_078_),
    .B(_097_),
    .Y(next_state[3])
  );
  NAND _261_ (
    .A(idle_out),
    .B(_070_),
    .Y(_098_)
  );
  NAND _262_ (
    .A(_084_),
    .B(_098_),
    .Y(next_idle)
  );
  NAND _263_ (
    .A(reset),
    .B(next_idle),
    .Y(_099_)
  );
  NOT _264_ (
    .A(_099_),
    .Y(_002_)
  );
  NOR _265_ (
    .A(error_out),
    .B(_077_),
    .Y(_100_)
  );
  NOR _266_ (
    .A(_080_),
    .B(_100_),
    .Y(next_error)
  );
  NAND _267_ (
    .A(reset),
    .B(next_error),
    .Y(_101_)
  );
  NOT _268_ (
    .A(_101_),
    .Y(_001_)
  );
  NAND _269_ (
    .A(_023_),
    .B(_081_),
    .Y(_003_[0])
  );
  NAND _270_ (
    .A(_078_),
    .B(_097_),
    .Y(_003_[3])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _271_ (
    .C(clk),
    .D(_001_),
    .Q(error_out)
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _272_ (
    .C(clk),
    .D(_000_),
    .Q(active_out)
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _273_ (
    .C(clk),
    .D(_002_),
    .Q(idle_out)
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _274_ (
    .C(clk),
    .D(_003_[0]),
    .Q(present_state[0])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _275_ (
    .C(clk),
    .D(_003_[1]),
    .Q(present_state[1])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _276_ (
    .C(clk),
    .D(_003_[2]),
    .Q(present_state[2])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _277_ (
    .C(clk),
    .D(_003_[3]),
    .Q(present_state[3])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _278_ (
    .C(clk),
    .D(_005_[0]),
    .Q(umbral_MFs_out[0])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _279_ (
    .C(clk),
    .D(_005_[1]),
    .Q(umbral_MFs_out[1])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _280_ (
    .C(clk),
    .D(_005_[2]),
    .Q(umbral_MFs_out[2])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _281_ (
    .C(clk),
    .D(_005_[3]),
    .Q(umbral_MFs_out[3])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _282_ (
    .C(clk),
    .D(_006_[0]),
    .Q(umbral_VCs_out[0])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _283_ (
    .C(clk),
    .D(_006_[1]),
    .Q(umbral_VCs_out[1])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _284_ (
    .C(clk),
    .D(_006_[2]),
    .Q(umbral_VCs_out[2])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _285_ (
    .C(clk),
    .D(_006_[3]),
    .Q(umbral_VCs_out[3])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _286_ (
    .C(clk),
    .D(_004_[0]),
    .Q(umbral_Ds_out[0])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _287_ (
    .C(clk),
    .D(_004_[1]),
    .Q(umbral_Ds_out[1])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _288_ (
    .C(clk),
    .D(_004_[2]),
    .Q(umbral_Ds_out[2])
  );
  (* src = "state_machine_synth.v:46" *)
  DFF _289_ (
    .C(clk),
    .D(_004_[3]),
    .Q(umbral_Ds_out[3])
  );
  assign FIFO_empties = { empty_main_fifo, empty_fifo_VC0, empty_fifo_VC1, empty_fifo_D0, empty_fifo_D1 };
  assign FIFO_errors = { error_main, error_VC0, error_VC1, error_D0, error_D1 };
endmodule
