/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* src = "VC0_fifo_synth.v:1" *)
module VC0_fifo_synth(clk, reset, wr_enable, rd_enable, data_in, Umbral_VC0, full_fifo_VC0, empty_fifo_VC0, almost_full_fifo_VC0, almost_empty_fifo_VC0, error_VC0, data_out_VC0);
  (* src = "VC0_fifo_synth.v:59" *)
  wire [2:0] _000_;
  (* src = "VC0_fifo_synth.v:44" *)
  wire [5:0] _001_;
  (* src = "VC0_fifo_synth.v:44" *)
  wire [1:0] _002_;
  (* src = "VC0_fifo_synth.v:31" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  (* src = "VC0_fifo_synth.v:8" *)
  input [3:0] Umbral_VC0;
  (* src = "VC0_fifo_synth.v:12" *)
  output almost_empty_fifo_VC0;
  (* src = "VC0_fifo_synth.v:11" *)
  output almost_full_fifo_VC0;
  (* src = "VC0_fifo_synth.v:6" *)
  input clk;
  (* src = "VC0_fifo_synth.v:21" *)
  wire [2:0] cnt;
  (* src = "VC0_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "VC0_fifo_synth.v:14" *)
  output [5:0] data_out_VC0;
  (* src = "VC0_fifo_synth.v:10" *)
  output empty_fifo_VC0;
  (* src = "VC0_fifo_synth.v:13" *)
  output error_VC0;
  (* src = "VC0_fifo_synth.v:9" *)
  output full_fifo_VC0;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "VC0_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "VC0_fifo_synth.v:20" *)
  wire [1:0] rd_ptr;
  (* src = "VC0_fifo_synth.v:6" *)
  input reset;
  (* src = "VC0_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "VC0_fifo_synth.v:19" *)
  wire [1:0] wr_ptr;
  NOT _240_ (
    .A(rd_enable),
    .Y(_227_)
  );
  NOT _241_ (
    .A(wr_enable),
    .Y(_228_)
  );
  NOT _242_ (
    .A(cnt[2]),
    .Y(_229_)
  );
  NOT _243_ (
    .A(cnt[0]),
    .Y(_230_)
  );
  NOT _244_ (
    .A(cnt[1]),
    .Y(_231_)
  );
  NOT _245_ (
    .A(\mem[3] [0]),
    .Y(_232_)
  );
  NOT _246_ (
    .A(\mem[3] [1]),
    .Y(_233_)
  );
  NOT _247_ (
    .A(\mem[3] [2]),
    .Y(_234_)
  );
  NOT _248_ (
    .A(\mem[3] [3]),
    .Y(_235_)
  );
  NOT _249_ (
    .A(\mem[3] [4]),
    .Y(_236_)
  );
  NOT _250_ (
    .A(\mem[3] [5]),
    .Y(_237_)
  );
  NOT _251_ (
    .A(rd_ptr[1]),
    .Y(_238_)
  );
  NOT _252_ (
    .A(reset),
    .Y(_239_)
  );
  NOT _253_ (
    .A(wr_ptr[1]),
    .Y(_028_)
  );
  NOT _254_ (
    .A(\mem[0] [0]),
    .Y(_029_)
  );
  NOT _255_ (
    .A(\mem[0] [1]),
    .Y(_030_)
  );
  NOT _256_ (
    .A(\mem[0] [2]),
    .Y(_031_)
  );
  NOT _257_ (
    .A(\mem[0] [3]),
    .Y(_032_)
  );
  NOT _258_ (
    .A(\mem[0] [4]),
    .Y(_033_)
  );
  NOT _259_ (
    .A(\mem[0] [5]),
    .Y(_034_)
  );
  NOT _260_ (
    .A(Umbral_VC0[0]),
    .Y(_035_)
  );
  NOT _261_ (
    .A(Umbral_VC0[2]),
    .Y(_036_)
  );
  NOR _262_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_037_)
  );
  NOT _263_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _264_ (
    .A(cnt[2]),
    .B(_037_),
    .Y(_039_)
  );
  NOT _265_ (
    .A(_039_),
    .Y(full_fifo_VC0)
  );
  NOR _266_ (
    .A(cnt[2]),
    .B(_038_),
    .Y(empty_fifo_VC0)
  );
  NAND _267_ (
    .A(_230_),
    .B(Umbral_VC0[0]),
    .Y(_040_)
  );
  NAND _268_ (
    .A(cnt[0]),
    .B(_035_),
    .Y(_041_)
  );
  NAND _269_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _270_ (
    .A(Umbral_VC0[3]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _271_ (
    .A(cnt[2]),
    .B(Umbral_VC0[2]),
    .Y(_044_)
  );
  NOT _272_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _273_ (
    .A(_229_),
    .B(_036_),
    .Y(_046_)
  );
  NOR _274_ (
    .A(_044_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _275_ (
    .A(cnt[1]),
    .B(Umbral_VC0[1]),
    .Y(_048_)
  );
  NOT _276_ (
    .A(_048_),
    .Y(_049_)
  );
  NAND _277_ (
    .A(cnt[1]),
    .B(Umbral_VC0[1]),
    .Y(_050_)
  );
  NOT _278_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _279_ (
    .A(_049_),
    .B(_050_),
    .Y(_052_)
  );
  NAND _280_ (
    .A(_043_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _281_ (
    .A(_047_),
    .B(_053_),
    .Y(almost_empty_fifo_VC0)
  );
  NAND _282_ (
    .A(_045_),
    .B(_048_),
    .Y(_054_)
  );
  NOR _283_ (
    .A(Umbral_VC0[0]),
    .B(_051_),
    .Y(_055_)
  );
  NAND _284_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _285_ (
    .A(Umbral_VC0[0]),
    .B(_052_),
    .Y(_057_)
  );
  NOR _286_ (
    .A(Umbral_VC0[0]),
    .B(Umbral_VC0[1]),
    .Y(_058_)
  );
  NOR _287_ (
    .A(_044_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _288_ (
    .A(_046_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _289_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _290_ (
    .A(_043_),
    .B(_056_),
    .Y(_062_)
  );
  NOR _291_ (
    .A(_061_),
    .B(_062_),
    .Y(almost_full_fifo_VC0)
  );
  NAND _292_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_063_)
  );
  NOT _293_ (
    .A(_063_),
    .Y(_064_)
  );
  NAND _294_ (
    .A(wr_ptr[1]),
    .B(_064_),
    .Y(_065_)
  );
  NOT _295_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _296_ (
    .A(_228_),
    .B(_239_),
    .Y(_067_)
  );
  NAND _297_ (
    .A(wr_enable),
    .B(reset),
    .Y(_068_)
  );
  NOR _298_ (
    .A(_239_),
    .B(_065_),
    .Y(_069_)
  );
  NAND _299_ (
    .A(reset),
    .B(_066_),
    .Y(_070_)
  );
  NAND _300_ (
    .A(data_in[0]),
    .B(_069_),
    .Y(_071_)
  );
  NAND _301_ (
    .A(\mem[3] [0]),
    .B(_070_),
    .Y(_072_)
  );
  NAND _302_ (
    .A(_071_),
    .B(_072_),
    .Y(_022_)
  );
  NAND _303_ (
    .A(data_in[1]),
    .B(_069_),
    .Y(_073_)
  );
  NAND _304_ (
    .A(\mem[3] [1]),
    .B(_070_),
    .Y(_074_)
  );
  NAND _305_ (
    .A(_073_),
    .B(_074_),
    .Y(_023_)
  );
  NAND _306_ (
    .A(data_in[2]),
    .B(_069_),
    .Y(_075_)
  );
  NAND _307_ (
    .A(\mem[3] [2]),
    .B(_070_),
    .Y(_076_)
  );
  NAND _308_ (
    .A(_075_),
    .B(_076_),
    .Y(_024_)
  );
  NAND _309_ (
    .A(data_in[3]),
    .B(_069_),
    .Y(_077_)
  );
  NAND _310_ (
    .A(\mem[3] [3]),
    .B(_070_),
    .Y(_078_)
  );
  NAND _311_ (
    .A(_077_),
    .B(_078_),
    .Y(_025_)
  );
  NAND _312_ (
    .A(data_in[4]),
    .B(_069_),
    .Y(_079_)
  );
  NAND _313_ (
    .A(\mem[3] [4]),
    .B(_070_),
    .Y(_080_)
  );
  NAND _314_ (
    .A(_079_),
    .B(_080_),
    .Y(_026_)
  );
  NAND _315_ (
    .A(data_in[5]),
    .B(_069_),
    .Y(_081_)
  );
  NAND _316_ (
    .A(\mem[3] [5]),
    .B(_070_),
    .Y(_082_)
  );
  NAND _317_ (
    .A(_081_),
    .B(_082_),
    .Y(_027_)
  );
  NOR _318_ (
    .A(_227_),
    .B(wr_enable),
    .Y(_083_)
  );
  NAND _319_ (
    .A(rd_enable),
    .B(_228_),
    .Y(_084_)
  );
  NOR _320_ (
    .A(rd_enable),
    .B(_228_),
    .Y(_085_)
  );
  NAND _321_ (
    .A(_227_),
    .B(wr_enable),
    .Y(_086_)
  );
  NOR _322_ (
    .A(_083_),
    .B(_085_),
    .Y(_087_)
  );
  NOR _323_ (
    .A(_230_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _324_ (
    .A(_230_),
    .B(_087_),
    .Y(_089_)
  );
  NAND _325_ (
    .A(reset),
    .B(_089_),
    .Y(_090_)
  );
  NOR _326_ (
    .A(_088_),
    .B(_090_),
    .Y(_000_[0])
  );
  NAND _327_ (
    .A(_230_),
    .B(_083_),
    .Y(_091_)
  );
  NOR _328_ (
    .A(_230_),
    .B(_086_),
    .Y(_092_)
  );
  NAND _329_ (
    .A(cnt[0]),
    .B(_085_),
    .Y(_093_)
  );
  NAND _330_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _331_ (
    .A(cnt[1]),
    .B(_094_),
    .Y(_095_)
  );
  NAND _332_ (
    .A(cnt[1]),
    .B(_094_),
    .Y(_096_)
  );
  NAND _333_ (
    .A(reset),
    .B(_096_),
    .Y(_097_)
  );
  NOR _334_ (
    .A(_095_),
    .B(_097_),
    .Y(_000_[1])
  );
  NOR _335_ (
    .A(_229_),
    .B(_037_),
    .Y(error_VC0)
  );
  NOR _336_ (
    .A(empty_fifo_VC0),
    .B(error_VC0),
    .Y(_098_)
  );
  NOR _337_ (
    .A(_084_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _338_ (
    .A(_231_),
    .B(_093_),
    .Y(_100_)
  );
  NAND _339_ (
    .A(cnt[1]),
    .B(_092_),
    .Y(_101_)
  );
  NOR _340_ (
    .A(_229_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _341_ (
    .A(_229_),
    .B(_083_),
    .Y(_103_)
  );
  NOR _342_ (
    .A(_100_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _343_ (
    .A(_102_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _344_ (
    .A(_099_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _345_ (
    .A(_239_),
    .B(_106_),
    .Y(_000_[2])
  );
  NAND _346_ (
    .A(rd_enable),
    .B(reset),
    .Y(_107_)
  );
  NOR _347_ (
    .A(\mem[2] [0]),
    .B(rd_ptr[0]),
    .Y(_108_)
  );
  NAND _348_ (
    .A(_232_),
    .B(rd_ptr[0]),
    .Y(_109_)
  );
  NAND _349_ (
    .A(rd_ptr[1]),
    .B(_109_),
    .Y(_110_)
  );
  NOR _350_ (
    .A(_108_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _351_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [0]),
    .Y(_112_)
  );
  NOT _352_ (
    .A(_112_),
    .Y(_113_)
  );
  NOR _353_ (
    .A(rd_ptr[0]),
    .B(_029_),
    .Y(_114_)
  );
  NOR _354_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _355_ (
    .A(rd_ptr[1]),
    .B(_115_),
    .Y(_116_)
  );
  NOR _356_ (
    .A(_111_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _357_ (
    .A(_107_),
    .B(_117_),
    .Y(_001_[0])
  );
  NOR _358_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_118_)
  );
  NAND _359_ (
    .A(rd_ptr[0]),
    .B(_233_),
    .Y(_119_)
  );
  NAND _360_ (
    .A(rd_ptr[1]),
    .B(_119_),
    .Y(_120_)
  );
  NOR _361_ (
    .A(_118_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _362_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_122_)
  );
  NOT _363_ (
    .A(_122_),
    .Y(_123_)
  );
  NOR _364_ (
    .A(rd_ptr[0]),
    .B(_030_),
    .Y(_124_)
  );
  NOR _365_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _366_ (
    .A(rd_ptr[1]),
    .B(_125_),
    .Y(_126_)
  );
  NOR _367_ (
    .A(_121_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _368_ (
    .A(_107_),
    .B(_127_),
    .Y(_001_[1])
  );
  NOR _369_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_128_)
  );
  NAND _370_ (
    .A(rd_ptr[0]),
    .B(_234_),
    .Y(_129_)
  );
  NAND _371_ (
    .A(rd_ptr[1]),
    .B(_129_),
    .Y(_130_)
  );
  NOR _372_ (
    .A(_128_),
    .B(_130_),
    .Y(_131_)
  );
  NAND _373_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_132_)
  );
  NOT _374_ (
    .A(_132_),
    .Y(_133_)
  );
  NOR _375_ (
    .A(rd_ptr[0]),
    .B(_031_),
    .Y(_134_)
  );
  NOR _376_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _377_ (
    .A(rd_ptr[1]),
    .B(_135_),
    .Y(_136_)
  );
  NOR _378_ (
    .A(_131_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _379_ (
    .A(_107_),
    .B(_137_),
    .Y(_001_[2])
  );
  NOR _380_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_138_)
  );
  NAND _381_ (
    .A(rd_ptr[0]),
    .B(_235_),
    .Y(_139_)
  );
  NAND _382_ (
    .A(rd_ptr[1]),
    .B(_139_),
    .Y(_140_)
  );
  NOR _383_ (
    .A(_138_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _384_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_142_)
  );
  NOT _385_ (
    .A(_142_),
    .Y(_143_)
  );
  NOR _386_ (
    .A(rd_ptr[0]),
    .B(_032_),
    .Y(_144_)
  );
  NOR _387_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _388_ (
    .A(rd_ptr[1]),
    .B(_145_),
    .Y(_146_)
  );
  NOR _389_ (
    .A(_141_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _390_ (
    .A(_107_),
    .B(_147_),
    .Y(_001_[3])
  );
  NOR _391_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_148_)
  );
  NAND _392_ (
    .A(rd_ptr[0]),
    .B(_236_),
    .Y(_149_)
  );
  NAND _393_ (
    .A(rd_ptr[1]),
    .B(_149_),
    .Y(_150_)
  );
  NOR _394_ (
    .A(_148_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _395_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_152_)
  );
  NOT _396_ (
    .A(_152_),
    .Y(_153_)
  );
  NOR _397_ (
    .A(rd_ptr[0]),
    .B(_033_),
    .Y(_154_)
  );
  NOR _398_ (
    .A(_153_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _399_ (
    .A(rd_ptr[1]),
    .B(_155_),
    .Y(_156_)
  );
  NOR _400_ (
    .A(_151_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _401_ (
    .A(_107_),
    .B(_157_),
    .Y(_001_[4])
  );
  NOR _402_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_158_)
  );
  NAND _403_ (
    .A(rd_ptr[0]),
    .B(_237_),
    .Y(_159_)
  );
  NAND _404_ (
    .A(rd_ptr[1]),
    .B(_159_),
    .Y(_160_)
  );
  NOR _405_ (
    .A(_158_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _406_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_162_)
  );
  NOT _407_ (
    .A(_162_),
    .Y(_163_)
  );
  NOR _408_ (
    .A(rd_ptr[0]),
    .B(_034_),
    .Y(_164_)
  );
  NOR _409_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _410_ (
    .A(rd_ptr[1]),
    .B(_165_),
    .Y(_166_)
  );
  NOR _411_ (
    .A(_161_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _412_ (
    .A(_107_),
    .B(_167_),
    .Y(_001_[5])
  );
  NAND _413_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_168_)
  );
  NOT _414_ (
    .A(_168_),
    .Y(_169_)
  );
  NOR _415_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_170_)
  );
  NOT _416_ (
    .A(_170_),
    .Y(_171_)
  );
  NAND _417_ (
    .A(reset),
    .B(_171_),
    .Y(_172_)
  );
  NOR _418_ (
    .A(_169_),
    .B(_172_),
    .Y(_002_[0])
  );
  NOR _419_ (
    .A(_238_),
    .B(_168_),
    .Y(_173_)
  );
  NAND _420_ (
    .A(_238_),
    .B(_168_),
    .Y(_174_)
  );
  NAND _421_ (
    .A(reset),
    .B(_174_),
    .Y(_175_)
  );
  NOR _422_ (
    .A(_173_),
    .B(_175_),
    .Y(_002_[1])
  );
  NOR _423_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_176_)
  );
  NAND _424_ (
    .A(reset),
    .B(_063_),
    .Y(_177_)
  );
  NOR _425_ (
    .A(_176_),
    .B(_177_),
    .Y(_003_[0])
  );
  NOR _426_ (
    .A(wr_ptr[1]),
    .B(_064_),
    .Y(_178_)
  );
  NOT _427_ (
    .A(_178_),
    .Y(_179_)
  );
  NAND _428_ (
    .A(reset),
    .B(_065_),
    .Y(_180_)
  );
  NOR _429_ (
    .A(_178_),
    .B(_180_),
    .Y(_003_[1])
  );
  NOR _430_ (
    .A(wr_ptr[0]),
    .B(_028_),
    .Y(_181_)
  );
  NAND _431_ (
    .A(wr_ptr[1]),
    .B(_067_),
    .Y(_182_)
  );
  NOR _432_ (
    .A(wr_ptr[0]),
    .B(_182_),
    .Y(_183_)
  );
  NAND _433_ (
    .A(_067_),
    .B(_181_),
    .Y(_184_)
  );
  NAND _434_ (
    .A(data_in[0]),
    .B(_183_),
    .Y(_185_)
  );
  NAND _435_ (
    .A(\mem[2] [0]),
    .B(_184_),
    .Y(_186_)
  );
  NAND _436_ (
    .A(_185_),
    .B(_186_),
    .Y(_016_)
  );
  NAND _437_ (
    .A(data_in[1]),
    .B(_183_),
    .Y(_187_)
  );
  NAND _438_ (
    .A(\mem[2] [1]),
    .B(_184_),
    .Y(_188_)
  );
  NAND _439_ (
    .A(_187_),
    .B(_188_),
    .Y(_017_)
  );
  NAND _440_ (
    .A(data_in[2]),
    .B(_183_),
    .Y(_189_)
  );
  NAND _441_ (
    .A(\mem[2] [2]),
    .B(_184_),
    .Y(_190_)
  );
  NAND _442_ (
    .A(_189_),
    .B(_190_),
    .Y(_018_)
  );
  NAND _443_ (
    .A(data_in[3]),
    .B(_183_),
    .Y(_191_)
  );
  NAND _444_ (
    .A(\mem[2] [3]),
    .B(_184_),
    .Y(_192_)
  );
  NAND _445_ (
    .A(_191_),
    .B(_192_),
    .Y(_019_)
  );
  NAND _446_ (
    .A(data_in[4]),
    .B(_183_),
    .Y(_193_)
  );
  NAND _447_ (
    .A(\mem[2] [4]),
    .B(_184_),
    .Y(_194_)
  );
  NAND _448_ (
    .A(_193_),
    .B(_194_),
    .Y(_020_)
  );
  NAND _449_ (
    .A(data_in[5]),
    .B(_183_),
    .Y(_195_)
  );
  NAND _450_ (
    .A(\mem[2] [5]),
    .B(_184_),
    .Y(_196_)
  );
  NAND _451_ (
    .A(_195_),
    .B(_196_),
    .Y(_021_)
  );
  NAND _452_ (
    .A(wr_ptr[0]),
    .B(_028_),
    .Y(_197_)
  );
  NOR _453_ (
    .A(_239_),
    .B(wr_ptr[1]),
    .Y(_198_)
  );
  NOR _454_ (
    .A(_068_),
    .B(_197_),
    .Y(_199_)
  );
  NAND _455_ (
    .A(_064_),
    .B(_198_),
    .Y(_200_)
  );
  NOR _456_ (
    .A(\mem[1] [0]),
    .B(_199_),
    .Y(_201_)
  );
  NOR _457_ (
    .A(data_in[0]),
    .B(_200_),
    .Y(_202_)
  );
  NOR _458_ (
    .A(_201_),
    .B(_202_),
    .Y(_010_)
  );
  NOR _459_ (
    .A(\mem[1] [1]),
    .B(_199_),
    .Y(_203_)
  );
  NOR _460_ (
    .A(data_in[1]),
    .B(_200_),
    .Y(_204_)
  );
  NOR _461_ (
    .A(_203_),
    .B(_204_),
    .Y(_011_)
  );
  NOR _462_ (
    .A(\mem[1] [2]),
    .B(_199_),
    .Y(_205_)
  );
  NOR _463_ (
    .A(data_in[2]),
    .B(_200_),
    .Y(_206_)
  );
  NOR _464_ (
    .A(_205_),
    .B(_206_),
    .Y(_012_)
  );
  NOR _465_ (
    .A(\mem[1] [3]),
    .B(_199_),
    .Y(_207_)
  );
  NOR _466_ (
    .A(data_in[3]),
    .B(_200_),
    .Y(_208_)
  );
  NOR _467_ (
    .A(_207_),
    .B(_208_),
    .Y(_013_)
  );
  NOR _468_ (
    .A(\mem[1] [4]),
    .B(_199_),
    .Y(_209_)
  );
  NOR _469_ (
    .A(data_in[4]),
    .B(_200_),
    .Y(_210_)
  );
  NOR _470_ (
    .A(_209_),
    .B(_210_),
    .Y(_014_)
  );
  NOR _471_ (
    .A(\mem[1] [5]),
    .B(_199_),
    .Y(_211_)
  );
  NOR _472_ (
    .A(data_in[5]),
    .B(_200_),
    .Y(_212_)
  );
  NOR _473_ (
    .A(_211_),
    .B(_212_),
    .Y(_015_)
  );
  NOR _474_ (
    .A(_068_),
    .B(_179_),
    .Y(_213_)
  );
  NAND _475_ (
    .A(_067_),
    .B(_178_),
    .Y(_214_)
  );
  NOR _476_ (
    .A(\mem[0] [0]),
    .B(_213_),
    .Y(_215_)
  );
  NOR _477_ (
    .A(data_in[0]),
    .B(_214_),
    .Y(_216_)
  );
  NOR _478_ (
    .A(_215_),
    .B(_216_),
    .Y(_004_)
  );
  NOR _479_ (
    .A(\mem[0] [1]),
    .B(_213_),
    .Y(_217_)
  );
  NOR _480_ (
    .A(data_in[1]),
    .B(_214_),
    .Y(_218_)
  );
  NOR _481_ (
    .A(_217_),
    .B(_218_),
    .Y(_005_)
  );
  NOR _482_ (
    .A(\mem[0] [2]),
    .B(_213_),
    .Y(_219_)
  );
  NOR _483_ (
    .A(data_in[2]),
    .B(_214_),
    .Y(_220_)
  );
  NOR _484_ (
    .A(_219_),
    .B(_220_),
    .Y(_006_)
  );
  NOR _485_ (
    .A(\mem[0] [3]),
    .B(_213_),
    .Y(_221_)
  );
  NOR _486_ (
    .A(data_in[3]),
    .B(_214_),
    .Y(_222_)
  );
  NOR _487_ (
    .A(_221_),
    .B(_222_),
    .Y(_007_)
  );
  NOR _488_ (
    .A(\mem[0] [4]),
    .B(_213_),
    .Y(_223_)
  );
  NOR _489_ (
    .A(data_in[4]),
    .B(_214_),
    .Y(_224_)
  );
  NOR _490_ (
    .A(_223_),
    .B(_224_),
    .Y(_008_)
  );
  NOR _491_ (
    .A(\mem[0] [5]),
    .B(_213_),
    .Y(_225_)
  );
  NOR _492_ (
    .A(data_in[5]),
    .B(_214_),
    .Y(_226_)
  );
  NOR _493_ (
    .A(_225_),
    .B(_226_),
    .Y(_009_)
  );
  DFF _494_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _495_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _496_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _497_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _498_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _499_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  DFF _500_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _501_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _502_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _503_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _504_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _505_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _506_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _507_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _508_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _509_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _510_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _511_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _512_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _513_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _514_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _515_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _516_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _517_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  (* src = "VC0_fifo_synth.v:59" *)
  DFF _518_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "VC0_fifo_synth.v:59" *)
  DFF _519_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "VC0_fifo_synth.v:59" *)
  DFF _520_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _521_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_VC0[0])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _522_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_VC0[1])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _523_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_VC0[2])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _524_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_VC0[3])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _525_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_VC0[4])
  );
  (* src = "VC0_fifo_synth.v:44" *)
  DFF _526_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_VC0[5])
  );
  (* src = "VC0_fifo_synth.v:31" *)
  DFF _527_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "VC0_fifo_synth.v:31" *)
  DFF _528_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  DFF _529_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _530_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
endmodule

(* dynports =  1  *)
(* src = "VC1_fifo_synth.v:1" *)
module VC1_fifo_synth(clk, reset, wr_enable, rd_enable, data_in, Umbral_VC1, full_fifo_VC1, empty_fifo_VC1, almost_full_fifo_VC1, almost_empty_fifo_VC1, error_VC1, data_out_VC1);
  (* src = "VC1_fifo_synth.v:59" *)
  wire [2:0] _000_;
  (* src = "VC1_fifo_synth.v:44" *)
  wire [5:0] _001_;
  (* src = "VC1_fifo_synth.v:44" *)
  wire [1:0] _002_;
  (* src = "VC1_fifo_synth.v:31" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  (* src = "VC1_fifo_synth.v:8" *)
  input [3:0] Umbral_VC1;
  (* src = "VC1_fifo_synth.v:12" *)
  output almost_empty_fifo_VC1;
  (* src = "VC1_fifo_synth.v:11" *)
  output almost_full_fifo_VC1;
  (* src = "VC1_fifo_synth.v:6" *)
  input clk;
  (* src = "VC1_fifo_synth.v:21" *)
  wire [2:0] cnt;
  (* src = "VC1_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "VC1_fifo_synth.v:14" *)
  output [5:0] data_out_VC1;
  (* src = "VC1_fifo_synth.v:10" *)
  output empty_fifo_VC1;
  (* src = "VC1_fifo_synth.v:13" *)
  output error_VC1;
  (* src = "VC1_fifo_synth.v:9" *)
  output full_fifo_VC1;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "VC1_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "VC1_fifo_synth.v:20" *)
  wire [1:0] rd_ptr;
  (* src = "VC1_fifo_synth.v:6" *)
  input reset;
  (* src = "VC1_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "VC1_fifo_synth.v:19" *)
  wire [1:0] wr_ptr;
  NOT _240_ (
    .A(rd_enable),
    .Y(_227_)
  );
  NOT _241_ (
    .A(cnt[2]),
    .Y(_228_)
  );
  NOT _242_ (
    .A(cnt[0]),
    .Y(_229_)
  );
  NOT _243_ (
    .A(cnt[1]),
    .Y(_230_)
  );
  NOT _244_ (
    .A(wr_enable),
    .Y(_231_)
  );
  NOT _245_ (
    .A(\mem[0] [0]),
    .Y(_232_)
  );
  NOT _246_ (
    .A(\mem[0] [1]),
    .Y(_233_)
  );
  NOT _247_ (
    .A(\mem[0] [2]),
    .Y(_234_)
  );
  NOT _248_ (
    .A(\mem[0] [3]),
    .Y(_235_)
  );
  NOT _249_ (
    .A(\mem[0] [4]),
    .Y(_236_)
  );
  NOT _250_ (
    .A(\mem[0] [5]),
    .Y(_237_)
  );
  NOT _251_ (
    .A(reset),
    .Y(_238_)
  );
  NOT _252_ (
    .A(rd_ptr[1]),
    .Y(_239_)
  );
  NOT _253_ (
    .A(wr_ptr[1]),
    .Y(_028_)
  );
  NOT _254_ (
    .A(\mem[3] [0]),
    .Y(_029_)
  );
  NOT _255_ (
    .A(\mem[3] [1]),
    .Y(_030_)
  );
  NOT _256_ (
    .A(\mem[3] [2]),
    .Y(_031_)
  );
  NOT _257_ (
    .A(\mem[3] [3]),
    .Y(_032_)
  );
  NOT _258_ (
    .A(\mem[3] [4]),
    .Y(_033_)
  );
  NOT _259_ (
    .A(\mem[3] [5]),
    .Y(_034_)
  );
  NOT _260_ (
    .A(Umbral_VC1[0]),
    .Y(_035_)
  );
  NOT _261_ (
    .A(Umbral_VC1[2]),
    .Y(_036_)
  );
  NOR _262_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_037_)
  );
  NOT _263_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _264_ (
    .A(cnt[2]),
    .B(_037_),
    .Y(_039_)
  );
  NOT _265_ (
    .A(_039_),
    .Y(full_fifo_VC1)
  );
  NOR _266_ (
    .A(cnt[2]),
    .B(_038_),
    .Y(empty_fifo_VC1)
  );
  NAND _267_ (
    .A(_229_),
    .B(Umbral_VC1[0]),
    .Y(_040_)
  );
  NOR _268_ (
    .A(_229_),
    .B(Umbral_VC1[0]),
    .Y(_041_)
  );
  NOR _269_ (
    .A(Umbral_VC1[3]),
    .B(_041_),
    .Y(_042_)
  );
  NAND _270_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _271_ (
    .A(_228_),
    .B(_036_),
    .Y(_044_)
  );
  NAND _272_ (
    .A(cnt[2]),
    .B(Umbral_VC1[2]),
    .Y(_045_)
  );
  NAND _273_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _274_ (
    .A(cnt[1]),
    .B(Umbral_VC1[1]),
    .Y(_047_)
  );
  NOT _275_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _276_ (
    .A(cnt[1]),
    .B(Umbral_VC1[1]),
    .Y(_049_)
  );
  NOT _277_ (
    .A(_049_),
    .Y(_050_)
  );
  NAND _278_ (
    .A(_048_),
    .B(_049_),
    .Y(_051_)
  );
  NAND _279_ (
    .A(_046_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _280_ (
    .A(_043_),
    .B(_052_),
    .Y(almost_empty_fifo_VC1)
  );
  NOR _281_ (
    .A(_044_),
    .B(_051_),
    .Y(_053_)
  );
  NOR _282_ (
    .A(_035_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _283_ (
    .A(_044_),
    .B(_047_),
    .Y(_055_)
  );
  NOR _284_ (
    .A(Umbral_VC1[0]),
    .B(_050_),
    .Y(_056_)
  );
  NAND _285_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _286_ (
    .A(Umbral_VC1[1]),
    .B(_044_),
    .Y(_058_)
  );
  NAND _287_ (
    .A(_045_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _288_ (
    .A(_043_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _289_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _290_ (
    .A(_054_),
    .B(_061_),
    .Y(almost_full_fifo_VC1)
  );
  NOR _291_ (
    .A(_231_),
    .B(_238_),
    .Y(_062_)
  );
  NAND _292_ (
    .A(wr_enable),
    .B(reset),
    .Y(_063_)
  );
  NAND _293_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_064_)
  );
  NOT _294_ (
    .A(_064_),
    .Y(_065_)
  );
  NOR _295_ (
    .A(wr_ptr[1]),
    .B(_065_),
    .Y(_066_)
  );
  NOT _296_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _297_ (
    .A(_063_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _298_ (
    .A(_062_),
    .B(_066_),
    .Y(_069_)
  );
  NAND _299_ (
    .A(data_in[0]),
    .B(_068_),
    .Y(_070_)
  );
  NAND _300_ (
    .A(\mem[0] [0]),
    .B(_069_),
    .Y(_071_)
  );
  NAND _301_ (
    .A(_070_),
    .B(_071_),
    .Y(_004_)
  );
  NAND _302_ (
    .A(data_in[1]),
    .B(_068_),
    .Y(_072_)
  );
  NAND _303_ (
    .A(\mem[0] [1]),
    .B(_069_),
    .Y(_073_)
  );
  NAND _304_ (
    .A(_072_),
    .B(_073_),
    .Y(_005_)
  );
  NAND _305_ (
    .A(data_in[2]),
    .B(_068_),
    .Y(_074_)
  );
  NAND _306_ (
    .A(\mem[0] [2]),
    .B(_069_),
    .Y(_075_)
  );
  NAND _307_ (
    .A(_074_),
    .B(_075_),
    .Y(_006_)
  );
  NAND _308_ (
    .A(data_in[3]),
    .B(_068_),
    .Y(_076_)
  );
  NAND _309_ (
    .A(\mem[0] [3]),
    .B(_069_),
    .Y(_077_)
  );
  NAND _310_ (
    .A(_076_),
    .B(_077_),
    .Y(_007_)
  );
  NAND _311_ (
    .A(data_in[4]),
    .B(_068_),
    .Y(_078_)
  );
  NAND _312_ (
    .A(\mem[0] [4]),
    .B(_069_),
    .Y(_079_)
  );
  NAND _313_ (
    .A(_078_),
    .B(_079_),
    .Y(_008_)
  );
  NAND _314_ (
    .A(data_in[5]),
    .B(_068_),
    .Y(_080_)
  );
  NAND _315_ (
    .A(\mem[0] [5]),
    .B(_069_),
    .Y(_081_)
  );
  NAND _316_ (
    .A(_080_),
    .B(_081_),
    .Y(_009_)
  );
  NAND _317_ (
    .A(rd_enable),
    .B(_229_),
    .Y(_082_)
  );
  NOR _318_ (
    .A(rd_enable),
    .B(_229_),
    .Y(_083_)
  );
  NAND _319_ (
    .A(_227_),
    .B(cnt[0]),
    .Y(_084_)
  );
  NAND _320_ (
    .A(_082_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _321_ (
    .A(wr_enable),
    .B(_085_),
    .Y(_086_)
  );
  NAND _322_ (
    .A(wr_enable),
    .B(_085_),
    .Y(_087_)
  );
  NAND _323_ (
    .A(reset),
    .B(_087_),
    .Y(_088_)
  );
  NOR _324_ (
    .A(_086_),
    .B(_088_),
    .Y(_000_[0])
  );
  NOR _325_ (
    .A(_231_),
    .B(_084_),
    .Y(_089_)
  );
  NAND _326_ (
    .A(wr_enable),
    .B(_083_),
    .Y(_090_)
  );
  NOR _327_ (
    .A(wr_enable),
    .B(_082_),
    .Y(_091_)
  );
  NOR _328_ (
    .A(_089_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _329_ (
    .A(_230_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _330_ (
    .A(_230_),
    .B(_092_),
    .Y(_094_)
  );
  NAND _331_ (
    .A(reset),
    .B(_093_),
    .Y(_095_)
  );
  NOR _332_ (
    .A(_094_),
    .B(_095_),
    .Y(_000_[1])
  );
  NOR _333_ (
    .A(_227_),
    .B(wr_enable),
    .Y(_096_)
  );
  NAND _334_ (
    .A(rd_enable),
    .B(_231_),
    .Y(_097_)
  );
  NOR _335_ (
    .A(_228_),
    .B(_037_),
    .Y(error_VC1)
  );
  NOR _336_ (
    .A(empty_fifo_VC1),
    .B(error_VC1),
    .Y(_098_)
  );
  NOR _337_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _338_ (
    .A(_230_),
    .B(_090_),
    .Y(_100_)
  );
  NAND _339_ (
    .A(cnt[1]),
    .B(_089_),
    .Y(_101_)
  );
  NOR _340_ (
    .A(_228_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _341_ (
    .A(_228_),
    .B(_096_),
    .Y(_103_)
  );
  NOR _342_ (
    .A(_100_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _343_ (
    .A(_102_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _344_ (
    .A(_099_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _345_ (
    .A(_238_),
    .B(_106_),
    .Y(_000_[2])
  );
  NAND _346_ (
    .A(rd_enable),
    .B(reset),
    .Y(_107_)
  );
  NOR _347_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [0]),
    .Y(_108_)
  );
  NAND _348_ (
    .A(rd_ptr[0]),
    .B(_029_),
    .Y(_109_)
  );
  NAND _349_ (
    .A(rd_ptr[1]),
    .B(_109_),
    .Y(_110_)
  );
  NOR _350_ (
    .A(_108_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _351_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [0]),
    .Y(_112_)
  );
  NOT _352_ (
    .A(_112_),
    .Y(_113_)
  );
  NOR _353_ (
    .A(_232_),
    .B(rd_ptr[0]),
    .Y(_114_)
  );
  NOR _354_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _355_ (
    .A(rd_ptr[1]),
    .B(_115_),
    .Y(_116_)
  );
  NOR _356_ (
    .A(_111_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _357_ (
    .A(_107_),
    .B(_117_),
    .Y(_001_[0])
  );
  NOR _358_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_118_)
  );
  NAND _359_ (
    .A(rd_ptr[0]),
    .B(_030_),
    .Y(_119_)
  );
  NAND _360_ (
    .A(rd_ptr[1]),
    .B(_119_),
    .Y(_120_)
  );
  NOR _361_ (
    .A(_118_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _362_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_122_)
  );
  NOT _363_ (
    .A(_122_),
    .Y(_123_)
  );
  NOR _364_ (
    .A(_233_),
    .B(rd_ptr[0]),
    .Y(_124_)
  );
  NOR _365_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _366_ (
    .A(rd_ptr[1]),
    .B(_125_),
    .Y(_126_)
  );
  NOR _367_ (
    .A(_121_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _368_ (
    .A(_107_),
    .B(_127_),
    .Y(_001_[1])
  );
  NOR _369_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_128_)
  );
  NAND _370_ (
    .A(rd_ptr[0]),
    .B(_031_),
    .Y(_129_)
  );
  NAND _371_ (
    .A(rd_ptr[1]),
    .B(_129_),
    .Y(_130_)
  );
  NOR _372_ (
    .A(_128_),
    .B(_130_),
    .Y(_131_)
  );
  NAND _373_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_132_)
  );
  NOT _374_ (
    .A(_132_),
    .Y(_133_)
  );
  NOR _375_ (
    .A(_234_),
    .B(rd_ptr[0]),
    .Y(_134_)
  );
  NOR _376_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _377_ (
    .A(rd_ptr[1]),
    .B(_135_),
    .Y(_136_)
  );
  NOR _378_ (
    .A(_131_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _379_ (
    .A(_107_),
    .B(_137_),
    .Y(_001_[2])
  );
  NOR _380_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_138_)
  );
  NAND _381_ (
    .A(rd_ptr[0]),
    .B(_032_),
    .Y(_139_)
  );
  NAND _382_ (
    .A(rd_ptr[1]),
    .B(_139_),
    .Y(_140_)
  );
  NOR _383_ (
    .A(_138_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _384_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_142_)
  );
  NOT _385_ (
    .A(_142_),
    .Y(_143_)
  );
  NOR _386_ (
    .A(_235_),
    .B(rd_ptr[0]),
    .Y(_144_)
  );
  NOR _387_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _388_ (
    .A(rd_ptr[1]),
    .B(_145_),
    .Y(_146_)
  );
  NOR _389_ (
    .A(_141_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _390_ (
    .A(_107_),
    .B(_147_),
    .Y(_001_[3])
  );
  NOR _391_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_148_)
  );
  NAND _392_ (
    .A(rd_ptr[0]),
    .B(_033_),
    .Y(_149_)
  );
  NAND _393_ (
    .A(rd_ptr[1]),
    .B(_149_),
    .Y(_150_)
  );
  NOR _394_ (
    .A(_148_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _395_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_152_)
  );
  NOT _396_ (
    .A(_152_),
    .Y(_153_)
  );
  NOR _397_ (
    .A(_236_),
    .B(rd_ptr[0]),
    .Y(_154_)
  );
  NOR _398_ (
    .A(_153_),
    .B(_154_),
    .Y(_155_)
  );
  NOR _399_ (
    .A(rd_ptr[1]),
    .B(_155_),
    .Y(_156_)
  );
  NOR _400_ (
    .A(_151_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _401_ (
    .A(_107_),
    .B(_157_),
    .Y(_001_[4])
  );
  NOR _402_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_158_)
  );
  NAND _403_ (
    .A(rd_ptr[0]),
    .B(_034_),
    .Y(_159_)
  );
  NAND _404_ (
    .A(rd_ptr[1]),
    .B(_159_),
    .Y(_160_)
  );
  NOR _405_ (
    .A(_158_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _406_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_162_)
  );
  NOT _407_ (
    .A(_162_),
    .Y(_163_)
  );
  NOR _408_ (
    .A(_237_),
    .B(rd_ptr[0]),
    .Y(_164_)
  );
  NOR _409_ (
    .A(_163_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _410_ (
    .A(rd_ptr[1]),
    .B(_165_),
    .Y(_166_)
  );
  NOR _411_ (
    .A(_161_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _412_ (
    .A(_107_),
    .B(_167_),
    .Y(_001_[5])
  );
  NAND _413_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_168_)
  );
  NOT _414_ (
    .A(_168_),
    .Y(_169_)
  );
  NOR _415_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_170_)
  );
  NOT _416_ (
    .A(_170_),
    .Y(_171_)
  );
  NAND _417_ (
    .A(reset),
    .B(_171_),
    .Y(_172_)
  );
  NOR _418_ (
    .A(_169_),
    .B(_172_),
    .Y(_002_[0])
  );
  NOR _419_ (
    .A(_239_),
    .B(_168_),
    .Y(_173_)
  );
  NAND _420_ (
    .A(_239_),
    .B(_168_),
    .Y(_174_)
  );
  NAND _421_ (
    .A(reset),
    .B(_174_),
    .Y(_175_)
  );
  NOR _422_ (
    .A(_173_),
    .B(_175_),
    .Y(_002_[1])
  );
  NOR _423_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_176_)
  );
  NAND _424_ (
    .A(reset),
    .B(_064_),
    .Y(_177_)
  );
  NOR _425_ (
    .A(_176_),
    .B(_177_),
    .Y(_003_[0])
  );
  NAND _426_ (
    .A(wr_ptr[1]),
    .B(_065_),
    .Y(_178_)
  );
  NOT _427_ (
    .A(_178_),
    .Y(_179_)
  );
  NAND _428_ (
    .A(reset),
    .B(_178_),
    .Y(_180_)
  );
  NOR _429_ (
    .A(_066_),
    .B(_180_),
    .Y(_003_[1])
  );
  NOR _430_ (
    .A(_238_),
    .B(_178_),
    .Y(_181_)
  );
  NAND _431_ (
    .A(reset),
    .B(_179_),
    .Y(_182_)
  );
  NAND _432_ (
    .A(data_in[0]),
    .B(_181_),
    .Y(_183_)
  );
  NAND _433_ (
    .A(\mem[3] [0]),
    .B(_182_),
    .Y(_184_)
  );
  NAND _434_ (
    .A(_183_),
    .B(_184_),
    .Y(_022_)
  );
  NAND _435_ (
    .A(data_in[1]),
    .B(_181_),
    .Y(_185_)
  );
  NAND _436_ (
    .A(\mem[3] [1]),
    .B(_182_),
    .Y(_186_)
  );
  NAND _437_ (
    .A(_185_),
    .B(_186_),
    .Y(_023_)
  );
  NAND _438_ (
    .A(data_in[2]),
    .B(_181_),
    .Y(_187_)
  );
  NAND _439_ (
    .A(\mem[3] [2]),
    .B(_182_),
    .Y(_188_)
  );
  NAND _440_ (
    .A(_187_),
    .B(_188_),
    .Y(_024_)
  );
  NAND _441_ (
    .A(data_in[3]),
    .B(_181_),
    .Y(_189_)
  );
  NAND _442_ (
    .A(\mem[3] [3]),
    .B(_182_),
    .Y(_190_)
  );
  NAND _443_ (
    .A(_189_),
    .B(_190_),
    .Y(_025_)
  );
  NAND _444_ (
    .A(data_in[4]),
    .B(_181_),
    .Y(_191_)
  );
  NAND _445_ (
    .A(\mem[3] [4]),
    .B(_182_),
    .Y(_192_)
  );
  NAND _446_ (
    .A(_191_),
    .B(_192_),
    .Y(_026_)
  );
  NAND _447_ (
    .A(data_in[5]),
    .B(_181_),
    .Y(_193_)
  );
  NAND _448_ (
    .A(\mem[3] [5]),
    .B(_182_),
    .Y(_194_)
  );
  NAND _449_ (
    .A(_193_),
    .B(_194_),
    .Y(_027_)
  );
  NOR _450_ (
    .A(wr_ptr[0]),
    .B(_028_),
    .Y(_195_)
  );
  NAND _451_ (
    .A(wr_ptr[1]),
    .B(_062_),
    .Y(_196_)
  );
  NOR _452_ (
    .A(wr_ptr[0]),
    .B(_196_),
    .Y(_197_)
  );
  NAND _453_ (
    .A(_062_),
    .B(_195_),
    .Y(_198_)
  );
  NAND _454_ (
    .A(data_in[0]),
    .B(_197_),
    .Y(_199_)
  );
  NAND _455_ (
    .A(\mem[2] [0]),
    .B(_198_),
    .Y(_200_)
  );
  NAND _456_ (
    .A(_199_),
    .B(_200_),
    .Y(_016_)
  );
  NAND _457_ (
    .A(data_in[1]),
    .B(_197_),
    .Y(_201_)
  );
  NAND _458_ (
    .A(\mem[2] [1]),
    .B(_198_),
    .Y(_202_)
  );
  NAND _459_ (
    .A(_201_),
    .B(_202_),
    .Y(_017_)
  );
  NAND _460_ (
    .A(data_in[2]),
    .B(_197_),
    .Y(_203_)
  );
  NAND _461_ (
    .A(\mem[2] [2]),
    .B(_198_),
    .Y(_204_)
  );
  NAND _462_ (
    .A(_203_),
    .B(_204_),
    .Y(_018_)
  );
  NAND _463_ (
    .A(data_in[3]),
    .B(_197_),
    .Y(_205_)
  );
  NAND _464_ (
    .A(\mem[2] [3]),
    .B(_198_),
    .Y(_206_)
  );
  NAND _465_ (
    .A(_205_),
    .B(_206_),
    .Y(_019_)
  );
  NAND _466_ (
    .A(data_in[4]),
    .B(_197_),
    .Y(_207_)
  );
  NAND _467_ (
    .A(\mem[2] [4]),
    .B(_198_),
    .Y(_208_)
  );
  NAND _468_ (
    .A(_207_),
    .B(_208_),
    .Y(_020_)
  );
  NAND _469_ (
    .A(data_in[5]),
    .B(_197_),
    .Y(_209_)
  );
  NAND _470_ (
    .A(\mem[2] [5]),
    .B(_198_),
    .Y(_210_)
  );
  NAND _471_ (
    .A(_209_),
    .B(_210_),
    .Y(_021_)
  );
  NAND _472_ (
    .A(wr_ptr[0]),
    .B(_028_),
    .Y(_211_)
  );
  NOR _473_ (
    .A(_238_),
    .B(wr_ptr[1]),
    .Y(_212_)
  );
  NOR _474_ (
    .A(_063_),
    .B(_211_),
    .Y(_213_)
  );
  NAND _475_ (
    .A(_065_),
    .B(_212_),
    .Y(_214_)
  );
  NOR _476_ (
    .A(\mem[1] [0]),
    .B(_213_),
    .Y(_215_)
  );
  NOR _477_ (
    .A(data_in[0]),
    .B(_214_),
    .Y(_216_)
  );
  NOR _478_ (
    .A(_215_),
    .B(_216_),
    .Y(_010_)
  );
  NOR _479_ (
    .A(\mem[1] [1]),
    .B(_213_),
    .Y(_217_)
  );
  NOR _480_ (
    .A(data_in[1]),
    .B(_214_),
    .Y(_218_)
  );
  NOR _481_ (
    .A(_217_),
    .B(_218_),
    .Y(_011_)
  );
  NOR _482_ (
    .A(\mem[1] [2]),
    .B(_213_),
    .Y(_219_)
  );
  NOR _483_ (
    .A(data_in[2]),
    .B(_214_),
    .Y(_220_)
  );
  NOR _484_ (
    .A(_219_),
    .B(_220_),
    .Y(_012_)
  );
  NOR _485_ (
    .A(\mem[1] [3]),
    .B(_213_),
    .Y(_221_)
  );
  NOR _486_ (
    .A(data_in[3]),
    .B(_214_),
    .Y(_222_)
  );
  NOR _487_ (
    .A(_221_),
    .B(_222_),
    .Y(_013_)
  );
  NOR _488_ (
    .A(\mem[1] [4]),
    .B(_213_),
    .Y(_223_)
  );
  NOR _489_ (
    .A(data_in[4]),
    .B(_214_),
    .Y(_224_)
  );
  NOR _490_ (
    .A(_223_),
    .B(_224_),
    .Y(_014_)
  );
  NOR _491_ (
    .A(\mem[1] [5]),
    .B(_213_),
    .Y(_225_)
  );
  NOR _492_ (
    .A(data_in[5]),
    .B(_214_),
    .Y(_226_)
  );
  NOR _493_ (
    .A(_225_),
    .B(_226_),
    .Y(_015_)
  );
  DFF _494_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _495_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _496_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _497_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _498_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _499_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  DFF _500_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _501_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _502_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _503_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _504_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _505_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _506_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _507_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _508_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _509_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _510_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _511_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _512_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _513_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _514_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _515_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _516_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _517_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _518_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _519_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  (* src = "VC1_fifo_synth.v:59" *)
  DFF _520_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "VC1_fifo_synth.v:59" *)
  DFF _521_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "VC1_fifo_synth.v:59" *)
  DFF _522_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _523_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_VC1[0])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _524_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_VC1[1])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _525_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_VC1[2])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _526_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_VC1[3])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _527_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_VC1[4])
  );
  (* src = "VC1_fifo_synth.v:44" *)
  DFF _528_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_VC1[5])
  );
  (* src = "VC1_fifo_synth.v:31" *)
  DFF _529_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "VC1_fifo_synth.v:31" *)
  DFF _530_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
endmodule

(* src = "comb_initial_synth.v:1" *)
module comb_initial_synth(clk, reset, pause_vc0, pause_vc1, empty_main_fifo, pop_main_fifo, valid_pop_out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "comb_initial_synth.v:1" *)
  input clk;
  (* src = "comb_initial_synth.v:5" *)
  input empty_main_fifo;
  (* src = "comb_initial_synth.v:3" *)
  input pause_vc0;
  (* src = "comb_initial_synth.v:4" *)
  input pause_vc1;
  (* src = "comb_initial_synth.v:6" *)
  output pop_main_fifo;
  (* src = "comb_initial_synth.v:2" *)
  input reset;
  (* src = "comb_initial_synth.v:7" *)
  output valid_pop_out;
  NOT _4_ (
    .A(empty_main_fifo),
    .Y(_0_)
  );
  NAND _5_ (
    .A(_0_),
    .B(reset),
    .Y(_1_)
  );
  NOR _6_ (
    .A(pause_vc0),
    .B(pause_vc1),
    .Y(_2_)
  );
  NOT _7_ (
    .A(_2_),
    .Y(_3_)
  );
  NOR _8_ (
    .A(_1_),
    .B(_3_),
    .Y(pop_main_fifo)
  );
  (* src = "comb_initial_synth.v:17" *)
  DFF _9_ (
    .C(clk),
    .D(pop_main_fifo),
    .Q(valid_pop_out)
  );
endmodule

(* src = "demux_initial_synth.v:1" *)
module demux_initial_synth(clk, data_in_demux_initial, valid_pop_out, reset, data_out_demux_initial_vc0, data_out_demux_initial_vc1, push_vc0, push_vc1);
  (* src = "demux_initial_synth.v:10" *)
  wire [5:0] _00_;
  (* src = "demux_initial_synth.v:10" *)
  wire [5:0] _01_;
  (* src = "demux_initial_synth.v:10" *)
  wire _02_;
  (* src = "demux_initial_synth.v:10" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "demux_initial_synth.v:1" *)
  input clk;
  (* src = "demux_initial_synth.v:2" *)
  input [5:0] data_in_demux_initial;
  (* src = "demux_initial_synth.v:5" *)
  output [5:0] data_out_demux_initial_vc0;
  (* src = "demux_initial_synth.v:6" *)
  output [5:0] data_out_demux_initial_vc1;
  (* src = "demux_initial_synth.v:7" *)
  output push_vc0;
  (* src = "demux_initial_synth.v:8" *)
  output push_vc1;
  (* src = "demux_initial_synth.v:4" *)
  input reset;
  (* src = "demux_initial_synth.v:3" *)
  input valid_pop_out;
  NOT _17_ (
    .A(data_in_demux_initial[0]),
    .Y(_04_)
  );
  NOT _18_ (
    .A(data_in_demux_initial[1]),
    .Y(_05_)
  );
  NOT _19_ (
    .A(data_in_demux_initial[2]),
    .Y(_06_)
  );
  NOT _20_ (
    .A(data_in_demux_initial[3]),
    .Y(_07_)
  );
  NOT _21_ (
    .A(data_in_demux_initial[4]),
    .Y(_08_)
  );
  NAND _22_ (
    .A(valid_pop_out),
    .B(reset),
    .Y(_09_)
  );
  NOT _23_ (
    .A(_09_),
    .Y(_10_)
  );
  NOR _24_ (
    .A(data_in_demux_initial[5]),
    .B(_09_),
    .Y(_02_)
  );
  NAND _25_ (
    .A(data_in_demux_initial[0]),
    .B(_02_),
    .Y(_11_)
  );
  NOT _26_ (
    .A(_11_),
    .Y(_00_[0])
  );
  NAND _27_ (
    .A(data_in_demux_initial[1]),
    .B(_02_),
    .Y(_12_)
  );
  NOT _28_ (
    .A(_12_),
    .Y(_00_[1])
  );
  NAND _29_ (
    .A(data_in_demux_initial[2]),
    .B(_02_),
    .Y(_13_)
  );
  NOT _30_ (
    .A(_13_),
    .Y(_00_[2])
  );
  NAND _31_ (
    .A(data_in_demux_initial[3]),
    .B(_02_),
    .Y(_14_)
  );
  NOT _32_ (
    .A(_14_),
    .Y(_00_[3])
  );
  NAND _33_ (
    .A(data_in_demux_initial[4]),
    .B(_02_),
    .Y(_15_)
  );
  NOT _34_ (
    .A(_15_),
    .Y(_00_[4])
  );
  NAND _35_ (
    .A(data_in_demux_initial[5]),
    .B(_10_),
    .Y(_16_)
  );
  NOT _36_ (
    .A(_16_),
    .Y(_03_)
  );
  NOR _37_ (
    .A(_04_),
    .B(_16_),
    .Y(_01_[0])
  );
  NOR _38_ (
    .A(_05_),
    .B(_16_),
    .Y(_01_[1])
  );
  NOR _39_ (
    .A(_06_),
    .B(_16_),
    .Y(_01_[2])
  );
  NOR _40_ (
    .A(_07_),
    .B(_16_),
    .Y(_01_[3])
  );
  NOR _41_ (
    .A(_08_),
    .B(_16_),
    .Y(_01_[4])
  );
  NOT _42_ (
    .A(_16_),
    .Y(_01_[5])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _43_ (
    .C(clk),
    .D(_01_[0]),
    .Q(data_out_demux_initial_vc1[0])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _44_ (
    .C(clk),
    .D(_01_[1]),
    .Q(data_out_demux_initial_vc1[1])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _45_ (
    .C(clk),
    .D(_01_[2]),
    .Q(data_out_demux_initial_vc1[2])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _46_ (
    .C(clk),
    .D(_01_[3]),
    .Q(data_out_demux_initial_vc1[3])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _47_ (
    .C(clk),
    .D(_01_[4]),
    .Q(data_out_demux_initial_vc1[4])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _48_ (
    .C(clk),
    .D(_01_[5]),
    .Q(data_out_demux_initial_vc1[5])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _49_ (
    .C(clk),
    .D(_03_),
    .Q(push_vc1)
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _50_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out_demux_initial_vc0[0])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _51_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out_demux_initial_vc0[1])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out_demux_initial_vc0[2])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _53_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out_demux_initial_vc0[3])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _54_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out_demux_initial_vc0[4])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _55_ (
    .C(clk),
    .D(1'h0),
    .Q(data_out_demux_initial_vc0[5])
  );
  (* src = "demux_initial_synth.v:10" *)
  DFF _56_ (
    .C(clk),
    .D(_02_),
    .Q(push_vc0)
  );
  assign _00_[5] = 1'h0;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "initial_logic_synth.v:7" *)
module initial_logic_synth(clk, reset, wr_enable, data_in, pop_VC0_fifo, pop_VC1_fifo, Umbral_Main, Umbral_VC0, Umbral_VC1, error_main, empty_main_fifo, full_fifo_VC0, empty_fifo_VC0, almost_full_fifo_VC0, almost_empty_fifo_VC0, error_VC0, data_out_VC0, full_fifo_VC1, empty_fifo_VC1, almost_full_fifo_VC1, almost_empty_fifo_VC1, error_VC1, data_out_VC1);
  (* src = "initial_logic_synth.v:15" *)
  input [3:0] Umbral_Main;
  (* src = "initial_logic_synth.v:16" *)
  input [3:0] Umbral_VC0;
  (* src = "initial_logic_synth.v:17" *)
  input [3:0] Umbral_VC1;
  (* src = "initial_logic_synth.v:37" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo;
  (* src = "initial_logic_synth.v:23" *)
  output almost_empty_fifo_VC0;
  (* src = "initial_logic_synth.v:29" *)
  output almost_empty_fifo_VC1;
  (* src = "initial_logic_synth.v:37" *)
  (* unused_bits = "0" *)
  wire almost_full_fifo;
  (* src = "initial_logic_synth.v:22" *)
  output almost_full_fifo_VC0;
  (* src = "initial_logic_synth.v:28" *)
  output almost_full_fifo_VC1;
  (* src = "initial_logic_synth.v:12" *)
  input clk;
  (* src = "initial_logic_synth.v:13" *)
  input [5:0] data_in;
  (* src = "initial_logic_synth.v:38" *)
  wire [5:0] data_in_demux_initial;
  (* src = "initial_logic_synth.v:25" *)
  output [5:0] data_out_VC0;
  (* src = "initial_logic_synth.v:31" *)
  output [5:0] data_out_VC1;
  (* src = "initial_logic_synth.v:34" *)
  wire [5:0] data_out_demux_initial_vc0;
  (* src = "initial_logic_synth.v:35" *)
  wire [5:0] data_out_demux_initial_vc1;
  (* src = "initial_logic_synth.v:21" *)
  output empty_fifo_VC0;
  (* src = "initial_logic_synth.v:27" *)
  output empty_fifo_VC1;
  (* src = "initial_logic_synth.v:19" *)
  output empty_main_fifo;
  (* src = "initial_logic_synth.v:24" *)
  output error_VC0;
  (* src = "initial_logic_synth.v:30" *)
  output error_VC1;
  (* src = "initial_logic_synth.v:18" *)
  output error_main;
  (* src = "initial_logic_synth.v:37" *)
  (* unused_bits = "0" *)
  wire full_fifo;
  (* src = "initial_logic_synth.v:20" *)
  output full_fifo_VC0;
  (* src = "initial_logic_synth.v:26" *)
  output full_fifo_VC1;
  (* src = "initial_logic_synth.v:14" *)
  input pop_VC0_fifo;
  (* src = "initial_logic_synth.v:14" *)
  input pop_VC1_fifo;
  (* src = "initial_logic_synth.v:36" *)
  wire pop_main_fifo;
  (* src = "initial_logic_synth.v:39" *)
  wire push_vc0;
  (* src = "initial_logic_synth.v:39" *)
  wire push_vc1;
  (* src = "initial_logic_synth.v:12" *)
  input reset;
  (* src = "initial_logic_synth.v:36" *)
  wire valid_pop_out;
  (* src = "initial_logic_synth.v:12" *)
  input wr_enable;
  (* module_not_derived = 32'd1 *)
  (* src = "initial_logic_synth.v:48" *)
  comb_initial_synth comb_initial_1 (
    .clk(clk),
    .empty_main_fifo(empty_main_fifo),
    .pause_vc0(almost_full_fifo_VC0),
    .pause_vc1(almost_full_fifo_VC1),
    .pop_main_fifo(pop_main_fifo),
    .reset(reset),
    .valid_pop_out(valid_pop_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "initial_logic_synth.v:51" *)
  demux_initial_synth demux_initial_1 (
    .clk(clk),
    .data_in_demux_initial(data_in_demux_initial),
    .data_out_demux_initial_vc0(data_out_demux_initial_vc0),
    .data_out_demux_initial_vc1(data_out_demux_initial_vc1),
    .push_vc0(push_vc0),
    .push_vc1(push_vc1),
    .reset(reset),
    .valid_pop_out(valid_pop_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "initial_logic_synth.v:55" *)
  VC0_fifo_synth fifo_VC0 (
    .Umbral_VC0(Umbral_VC0),
    .almost_empty_fifo_VC0(almost_empty_fifo_VC0),
    .almost_full_fifo_VC0(almost_full_fifo_VC0),
    .clk(clk),
    .data_in(data_out_demux_initial_vc0),
    .data_out_VC0(data_out_VC0),
    .empty_fifo_VC0(empty_fifo_VC0),
    .error_VC0(error_VC0),
    .full_fifo_VC0(full_fifo_VC0),
    .rd_enable(pop_VC0_fifo),
    .reset(reset),
    .wr_enable(push_vc0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "initial_logic_synth.v:59" *)
  VC1_fifo_synth fifo_VC1 (
    .Umbral_VC1(Umbral_VC1),
    .almost_empty_fifo_VC1(almost_empty_fifo_VC1),
    .almost_full_fifo_VC1(almost_full_fifo_VC1),
    .clk(clk),
    .data_in(data_out_demux_initial_vc1),
    .data_out_VC1(data_out_VC1),
    .empty_fifo_VC1(empty_fifo_VC1),
    .error_VC1(error_VC1),
    .full_fifo_VC1(full_fifo_VC1),
    .rd_enable(pop_VC1_fifo),
    .reset(reset),
    .wr_enable(push_vc1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "initial_logic_synth.v:41" *)
  main_fifo_synth fifo_main (
    .Umbral_Main(Umbral_Main),
    .almost_empty_fifo(almost_empty_fifo),
    .almost_full_fifo(almost_full_fifo),
    .clk(clk),
    .data_in(data_in),
    .data_out(data_in_demux_initial),
    .empty_fifo(empty_main_fifo),
    .error(error_main),
    .full_fifo(full_fifo),
    .rd_enable(pop_main_fifo),
    .reset(reset),
    .wr_enable(wr_enable)
  );
endmodule

(* dynports =  1  *)
(* src = "main_fifo_synth.v:1" *)
module main_fifo_synth(clk, reset, wr_enable, rd_enable, data_in, Umbral_Main, full_fifo, empty_fifo, almost_full_fifo, almost_empty_fifo, error, data_out);
  (* src = "main_fifo_synth.v:59" *)
  wire [2:0] _000_;
  (* src = "main_fifo_synth.v:44" *)
  wire [5:0] _001_;
  (* src = "main_fifo_synth.v:44" *)
  wire [1:0] _002_;
  (* src = "main_fifo_synth.v:31" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  (* src = "main_fifo_synth.v:8" *)
  input [3:0] Umbral_Main;
  (* src = "main_fifo_synth.v:12" *)
  output almost_empty_fifo;
  (* src = "main_fifo_synth.v:11" *)
  output almost_full_fifo;
  (* src = "main_fifo_synth.v:6" *)
  input clk;
  (* src = "main_fifo_synth.v:21" *)
  wire [2:0] cnt;
  (* src = "main_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "main_fifo_synth.v:14" *)
  output [5:0] data_out;
  (* src = "main_fifo_synth.v:10" *)
  output empty_fifo;
  (* src = "main_fifo_synth.v:13" *)
  output error;
  (* src = "main_fifo_synth.v:9" *)
  output full_fifo;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "main_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "main_fifo_synth.v:20" *)
  wire [1:0] rd_ptr;
  (* src = "main_fifo_synth.v:6" *)
  input reset;
  (* src = "main_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "main_fifo_synth.v:19" *)
  wire [1:0] wr_ptr;
  NOT _240_ (
    .A(rd_enable),
    .Y(_227_)
  );
  NOT _241_ (
    .A(wr_enable),
    .Y(_228_)
  );
  NOT _242_ (
    .A(cnt[2]),
    .Y(_229_)
  );
  NOT _243_ (
    .A(cnt[0]),
    .Y(_230_)
  );
  NOT _244_ (
    .A(cnt[1]),
    .Y(_231_)
  );
  NOT _245_ (
    .A(\mem[3] [0]),
    .Y(_232_)
  );
  NOT _246_ (
    .A(\mem[3] [1]),
    .Y(_233_)
  );
  NOT _247_ (
    .A(\mem[3] [2]),
    .Y(_234_)
  );
  NOT _248_ (
    .A(\mem[3] [3]),
    .Y(_235_)
  );
  NOT _249_ (
    .A(\mem[3] [4]),
    .Y(_236_)
  );
  NOT _250_ (
    .A(\mem[3] [5]),
    .Y(_237_)
  );
  NOT _251_ (
    .A(rd_ptr[1]),
    .Y(_238_)
  );
  NOT _252_ (
    .A(\mem[0] [0]),
    .Y(_239_)
  );
  NOT _253_ (
    .A(\mem[0] [1]),
    .Y(_028_)
  );
  NOT _254_ (
    .A(\mem[0] [2]),
    .Y(_029_)
  );
  NOT _255_ (
    .A(\mem[0] [3]),
    .Y(_030_)
  );
  NOT _256_ (
    .A(\mem[0] [4]),
    .Y(_031_)
  );
  NOT _257_ (
    .A(\mem[0] [5]),
    .Y(_032_)
  );
  NOT _258_ (
    .A(reset),
    .Y(_033_)
  );
  NOT _259_ (
    .A(wr_ptr[1]),
    .Y(_034_)
  );
  NOT _260_ (
    .A(Umbral_Main[0]),
    .Y(_035_)
  );
  NOT _261_ (
    .A(Umbral_Main[2]),
    .Y(_036_)
  );
  NOR _262_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_037_)
  );
  NOT _263_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _264_ (
    .A(cnt[2]),
    .B(_037_),
    .Y(_039_)
  );
  NOT _265_ (
    .A(_039_),
    .Y(full_fifo)
  );
  NOR _266_ (
    .A(cnt[2]),
    .B(_038_),
    .Y(empty_fifo)
  );
  NAND _267_ (
    .A(_230_),
    .B(Umbral_Main[0]),
    .Y(_040_)
  );
  NAND _268_ (
    .A(cnt[0]),
    .B(_035_),
    .Y(_041_)
  );
  NAND _269_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _270_ (
    .A(Umbral_Main[3]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _271_ (
    .A(cnt[2]),
    .B(Umbral_Main[2]),
    .Y(_044_)
  );
  NOT _272_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _273_ (
    .A(_229_),
    .B(_036_),
    .Y(_046_)
  );
  NOR _274_ (
    .A(_044_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _275_ (
    .A(cnt[1]),
    .B(Umbral_Main[1]),
    .Y(_048_)
  );
  NOT _276_ (
    .A(_048_),
    .Y(_049_)
  );
  NAND _277_ (
    .A(cnt[1]),
    .B(Umbral_Main[1]),
    .Y(_050_)
  );
  NOT _278_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _279_ (
    .A(_049_),
    .B(_050_),
    .Y(_052_)
  );
  NAND _280_ (
    .A(_043_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _281_ (
    .A(_047_),
    .B(_053_),
    .Y(almost_empty_fifo)
  );
  NAND _282_ (
    .A(_045_),
    .B(_048_),
    .Y(_054_)
  );
  NOR _283_ (
    .A(Umbral_Main[0]),
    .B(_051_),
    .Y(_055_)
  );
  NAND _284_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _285_ (
    .A(Umbral_Main[0]),
    .B(_052_),
    .Y(_057_)
  );
  NOR _286_ (
    .A(Umbral_Main[0]),
    .B(Umbral_Main[1]),
    .Y(_058_)
  );
  NOR _287_ (
    .A(_044_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _288_ (
    .A(_046_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _289_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _290_ (
    .A(_043_),
    .B(_056_),
    .Y(_062_)
  );
  NOR _291_ (
    .A(_061_),
    .B(_062_),
    .Y(almost_full_fifo)
  );
  NAND _292_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_063_)
  );
  NOT _293_ (
    .A(_063_),
    .Y(_064_)
  );
  NAND _294_ (
    .A(wr_ptr[1]),
    .B(_064_),
    .Y(_065_)
  );
  NOT _295_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _296_ (
    .A(_228_),
    .B(_033_),
    .Y(_067_)
  );
  NAND _297_ (
    .A(wr_enable),
    .B(reset),
    .Y(_068_)
  );
  NOR _298_ (
    .A(_033_),
    .B(_065_),
    .Y(_069_)
  );
  NAND _299_ (
    .A(reset),
    .B(_066_),
    .Y(_070_)
  );
  NAND _300_ (
    .A(data_in[0]),
    .B(_069_),
    .Y(_071_)
  );
  NAND _301_ (
    .A(\mem[3] [0]),
    .B(_070_),
    .Y(_072_)
  );
  NAND _302_ (
    .A(_071_),
    .B(_072_),
    .Y(_022_)
  );
  NAND _303_ (
    .A(data_in[1]),
    .B(_069_),
    .Y(_073_)
  );
  NAND _304_ (
    .A(\mem[3] [1]),
    .B(_070_),
    .Y(_074_)
  );
  NAND _305_ (
    .A(_073_),
    .B(_074_),
    .Y(_023_)
  );
  NAND _306_ (
    .A(data_in[2]),
    .B(_069_),
    .Y(_075_)
  );
  NAND _307_ (
    .A(\mem[3] [2]),
    .B(_070_),
    .Y(_076_)
  );
  NAND _308_ (
    .A(_075_),
    .B(_076_),
    .Y(_024_)
  );
  NAND _309_ (
    .A(data_in[3]),
    .B(_069_),
    .Y(_077_)
  );
  NAND _310_ (
    .A(\mem[3] [3]),
    .B(_070_),
    .Y(_078_)
  );
  NAND _311_ (
    .A(_077_),
    .B(_078_),
    .Y(_025_)
  );
  NAND _312_ (
    .A(data_in[4]),
    .B(_069_),
    .Y(_079_)
  );
  NAND _313_ (
    .A(\mem[3] [4]),
    .B(_070_),
    .Y(_080_)
  );
  NAND _314_ (
    .A(_079_),
    .B(_080_),
    .Y(_026_)
  );
  NAND _315_ (
    .A(data_in[5]),
    .B(_069_),
    .Y(_081_)
  );
  NAND _316_ (
    .A(\mem[3] [5]),
    .B(_070_),
    .Y(_082_)
  );
  NAND _317_ (
    .A(_081_),
    .B(_082_),
    .Y(_027_)
  );
  NOR _318_ (
    .A(wr_ptr[0]),
    .B(_034_),
    .Y(_083_)
  );
  NAND _319_ (
    .A(wr_ptr[1]),
    .B(_067_),
    .Y(_084_)
  );
  NOR _320_ (
    .A(wr_ptr[0]),
    .B(_084_),
    .Y(_085_)
  );
  NAND _321_ (
    .A(_067_),
    .B(_083_),
    .Y(_086_)
  );
  NAND _322_ (
    .A(data_in[0]),
    .B(_085_),
    .Y(_087_)
  );
  NAND _323_ (
    .A(\mem[2] [0]),
    .B(_086_),
    .Y(_088_)
  );
  NAND _324_ (
    .A(_087_),
    .B(_088_),
    .Y(_016_)
  );
  NAND _325_ (
    .A(data_in[1]),
    .B(_085_),
    .Y(_089_)
  );
  NAND _326_ (
    .A(\mem[2] [1]),
    .B(_086_),
    .Y(_090_)
  );
  NAND _327_ (
    .A(_089_),
    .B(_090_),
    .Y(_017_)
  );
  NAND _328_ (
    .A(data_in[2]),
    .B(_085_),
    .Y(_091_)
  );
  NAND _329_ (
    .A(\mem[2] [2]),
    .B(_086_),
    .Y(_092_)
  );
  NAND _330_ (
    .A(_091_),
    .B(_092_),
    .Y(_018_)
  );
  NAND _331_ (
    .A(data_in[3]),
    .B(_085_),
    .Y(_093_)
  );
  NAND _332_ (
    .A(\mem[2] [3]),
    .B(_086_),
    .Y(_094_)
  );
  NAND _333_ (
    .A(_093_),
    .B(_094_),
    .Y(_019_)
  );
  NAND _334_ (
    .A(data_in[4]),
    .B(_085_),
    .Y(_095_)
  );
  NAND _335_ (
    .A(\mem[2] [4]),
    .B(_086_),
    .Y(_096_)
  );
  NAND _336_ (
    .A(_095_),
    .B(_096_),
    .Y(_020_)
  );
  NAND _337_ (
    .A(data_in[5]),
    .B(_085_),
    .Y(_097_)
  );
  NAND _338_ (
    .A(\mem[2] [5]),
    .B(_086_),
    .Y(_098_)
  );
  NAND _339_ (
    .A(_097_),
    .B(_098_),
    .Y(_021_)
  );
  NAND _340_ (
    .A(wr_ptr[0]),
    .B(_034_),
    .Y(_099_)
  );
  NOR _341_ (
    .A(_033_),
    .B(wr_ptr[1]),
    .Y(_100_)
  );
  NOR _342_ (
    .A(_068_),
    .B(_099_),
    .Y(_101_)
  );
  NAND _343_ (
    .A(_064_),
    .B(_100_),
    .Y(_102_)
  );
  NOR _344_ (
    .A(\mem[1] [0]),
    .B(_101_),
    .Y(_103_)
  );
  NOR _345_ (
    .A(data_in[0]),
    .B(_102_),
    .Y(_104_)
  );
  NOR _346_ (
    .A(_103_),
    .B(_104_),
    .Y(_010_)
  );
  NOR _347_ (
    .A(\mem[1] [1]),
    .B(_101_),
    .Y(_105_)
  );
  NOR _348_ (
    .A(data_in[1]),
    .B(_102_),
    .Y(_106_)
  );
  NOR _349_ (
    .A(_105_),
    .B(_106_),
    .Y(_011_)
  );
  NOR _350_ (
    .A(\mem[1] [2]),
    .B(_101_),
    .Y(_107_)
  );
  NOR _351_ (
    .A(data_in[2]),
    .B(_102_),
    .Y(_108_)
  );
  NOR _352_ (
    .A(_107_),
    .B(_108_),
    .Y(_012_)
  );
  NOR _353_ (
    .A(\mem[1] [3]),
    .B(_101_),
    .Y(_109_)
  );
  NOR _354_ (
    .A(data_in[3]),
    .B(_102_),
    .Y(_110_)
  );
  NOR _355_ (
    .A(_109_),
    .B(_110_),
    .Y(_013_)
  );
  NOR _356_ (
    .A(\mem[1] [4]),
    .B(_101_),
    .Y(_111_)
  );
  NOR _357_ (
    .A(data_in[4]),
    .B(_102_),
    .Y(_112_)
  );
  NOR _358_ (
    .A(_111_),
    .B(_112_),
    .Y(_014_)
  );
  NOR _359_ (
    .A(\mem[1] [5]),
    .B(_101_),
    .Y(_113_)
  );
  NOR _360_ (
    .A(data_in[5]),
    .B(_102_),
    .Y(_114_)
  );
  NOR _361_ (
    .A(_113_),
    .B(_114_),
    .Y(_015_)
  );
  NOR _362_ (
    .A(wr_ptr[1]),
    .B(_064_),
    .Y(_115_)
  );
  NOT _363_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _364_ (
    .A(_068_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _365_ (
    .A(_067_),
    .B(_115_),
    .Y(_118_)
  );
  NOR _366_ (
    .A(\mem[0] [0]),
    .B(_117_),
    .Y(_119_)
  );
  NOR _367_ (
    .A(data_in[0]),
    .B(_118_),
    .Y(_120_)
  );
  NOR _368_ (
    .A(_119_),
    .B(_120_),
    .Y(_004_)
  );
  NOR _369_ (
    .A(\mem[0] [1]),
    .B(_117_),
    .Y(_121_)
  );
  NOR _370_ (
    .A(data_in[1]),
    .B(_118_),
    .Y(_122_)
  );
  NOR _371_ (
    .A(_121_),
    .B(_122_),
    .Y(_005_)
  );
  NOR _372_ (
    .A(\mem[0] [2]),
    .B(_117_),
    .Y(_123_)
  );
  NOR _373_ (
    .A(data_in[2]),
    .B(_118_),
    .Y(_124_)
  );
  NOR _374_ (
    .A(_123_),
    .B(_124_),
    .Y(_006_)
  );
  NOR _375_ (
    .A(\mem[0] [3]),
    .B(_117_),
    .Y(_125_)
  );
  NOR _376_ (
    .A(data_in[3]),
    .B(_118_),
    .Y(_126_)
  );
  NOR _377_ (
    .A(_125_),
    .B(_126_),
    .Y(_007_)
  );
  NOR _378_ (
    .A(\mem[0] [4]),
    .B(_117_),
    .Y(_127_)
  );
  NOR _379_ (
    .A(data_in[4]),
    .B(_118_),
    .Y(_128_)
  );
  NOR _380_ (
    .A(_127_),
    .B(_128_),
    .Y(_008_)
  );
  NOR _381_ (
    .A(\mem[0] [5]),
    .B(_117_),
    .Y(_129_)
  );
  NOR _382_ (
    .A(data_in[5]),
    .B(_118_),
    .Y(_130_)
  );
  NOR _383_ (
    .A(_129_),
    .B(_130_),
    .Y(_009_)
  );
  NOR _384_ (
    .A(_227_),
    .B(wr_enable),
    .Y(_131_)
  );
  NAND _385_ (
    .A(rd_enable),
    .B(_228_),
    .Y(_132_)
  );
  NOR _386_ (
    .A(rd_enable),
    .B(_228_),
    .Y(_133_)
  );
  NAND _387_ (
    .A(_227_),
    .B(wr_enable),
    .Y(_134_)
  );
  NOR _388_ (
    .A(_131_),
    .B(_133_),
    .Y(_135_)
  );
  NOR _389_ (
    .A(_230_),
    .B(_135_),
    .Y(_136_)
  );
  NAND _390_ (
    .A(_230_),
    .B(_135_),
    .Y(_137_)
  );
  NAND _391_ (
    .A(reset),
    .B(_137_),
    .Y(_138_)
  );
  NOR _392_ (
    .A(_136_),
    .B(_138_),
    .Y(_000_[0])
  );
  NAND _393_ (
    .A(_230_),
    .B(_131_),
    .Y(_139_)
  );
  NOR _394_ (
    .A(_230_),
    .B(_134_),
    .Y(_140_)
  );
  NAND _395_ (
    .A(cnt[0]),
    .B(_133_),
    .Y(_141_)
  );
  NAND _396_ (
    .A(_139_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _397_ (
    .A(cnt[1]),
    .B(_142_),
    .Y(_143_)
  );
  NAND _398_ (
    .A(cnt[1]),
    .B(_142_),
    .Y(_144_)
  );
  NAND _399_ (
    .A(reset),
    .B(_144_),
    .Y(_145_)
  );
  NOR _400_ (
    .A(_143_),
    .B(_145_),
    .Y(_000_[1])
  );
  NOR _401_ (
    .A(_229_),
    .B(_037_),
    .Y(error)
  );
  NOR _402_ (
    .A(empty_fifo),
    .B(error),
    .Y(_146_)
  );
  NOR _403_ (
    .A(_132_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _404_ (
    .A(_231_),
    .B(_141_),
    .Y(_148_)
  );
  NAND _405_ (
    .A(cnt[1]),
    .B(_140_),
    .Y(_149_)
  );
  NOR _406_ (
    .A(_229_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _407_ (
    .A(_229_),
    .B(_131_),
    .Y(_151_)
  );
  NOR _408_ (
    .A(_148_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _409_ (
    .A(_150_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _410_ (
    .A(_147_),
    .B(_153_),
    .Y(_154_)
  );
  NOR _411_ (
    .A(_033_),
    .B(_154_),
    .Y(_000_[2])
  );
  NAND _412_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_155_)
  );
  NOT _413_ (
    .A(_155_),
    .Y(_156_)
  );
  NOR _414_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_157_)
  );
  NOT _415_ (
    .A(_157_),
    .Y(_158_)
  );
  NAND _416_ (
    .A(reset),
    .B(_158_),
    .Y(_159_)
  );
  NOR _417_ (
    .A(_156_),
    .B(_159_),
    .Y(_002_[0])
  );
  NOR _418_ (
    .A(_238_),
    .B(_155_),
    .Y(_160_)
  );
  NAND _419_ (
    .A(_238_),
    .B(_155_),
    .Y(_161_)
  );
  NAND _420_ (
    .A(reset),
    .B(_161_),
    .Y(_162_)
  );
  NOR _421_ (
    .A(_160_),
    .B(_162_),
    .Y(_002_[1])
  );
  NAND _422_ (
    .A(rd_enable),
    .B(reset),
    .Y(_163_)
  );
  NOR _423_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [0]),
    .Y(_164_)
  );
  NAND _424_ (
    .A(_232_),
    .B(rd_ptr[0]),
    .Y(_165_)
  );
  NAND _425_ (
    .A(rd_ptr[1]),
    .B(_165_),
    .Y(_166_)
  );
  NOR _426_ (
    .A(_164_),
    .B(_166_),
    .Y(_167_)
  );
  NAND _427_ (
    .A(\mem[1] [0]),
    .B(rd_ptr[0]),
    .Y(_168_)
  );
  NOT _428_ (
    .A(_168_),
    .Y(_169_)
  );
  NOR _429_ (
    .A(_239_),
    .B(rd_ptr[0]),
    .Y(_170_)
  );
  NOR _430_ (
    .A(_169_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _431_ (
    .A(rd_ptr[1]),
    .B(_171_),
    .Y(_172_)
  );
  NOR _432_ (
    .A(_167_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _433_ (
    .A(_163_),
    .B(_173_),
    .Y(_001_[0])
  );
  NOR _434_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_174_)
  );
  NAND _435_ (
    .A(_233_),
    .B(rd_ptr[0]),
    .Y(_175_)
  );
  NAND _436_ (
    .A(rd_ptr[1]),
    .B(_175_),
    .Y(_176_)
  );
  NOR _437_ (
    .A(_174_),
    .B(_176_),
    .Y(_177_)
  );
  NAND _438_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_178_)
  );
  NOT _439_ (
    .A(_178_),
    .Y(_179_)
  );
  NOR _440_ (
    .A(rd_ptr[0]),
    .B(_028_),
    .Y(_180_)
  );
  NOR _441_ (
    .A(_179_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _442_ (
    .A(rd_ptr[1]),
    .B(_181_),
    .Y(_182_)
  );
  NOR _443_ (
    .A(_177_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _444_ (
    .A(_163_),
    .B(_183_),
    .Y(_001_[1])
  );
  NOR _445_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_184_)
  );
  NAND _446_ (
    .A(_234_),
    .B(rd_ptr[0]),
    .Y(_185_)
  );
  NAND _447_ (
    .A(rd_ptr[1]),
    .B(_185_),
    .Y(_186_)
  );
  NOR _448_ (
    .A(_184_),
    .B(_186_),
    .Y(_187_)
  );
  NAND _449_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_188_)
  );
  NOT _450_ (
    .A(_188_),
    .Y(_189_)
  );
  NOR _451_ (
    .A(rd_ptr[0]),
    .B(_029_),
    .Y(_190_)
  );
  NOR _452_ (
    .A(_189_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _453_ (
    .A(rd_ptr[1]),
    .B(_191_),
    .Y(_192_)
  );
  NOR _454_ (
    .A(_187_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _455_ (
    .A(_163_),
    .B(_193_),
    .Y(_001_[2])
  );
  NOR _456_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_194_)
  );
  NAND _457_ (
    .A(_235_),
    .B(rd_ptr[0]),
    .Y(_195_)
  );
  NAND _458_ (
    .A(rd_ptr[1]),
    .B(_195_),
    .Y(_196_)
  );
  NOR _459_ (
    .A(_194_),
    .B(_196_),
    .Y(_197_)
  );
  NAND _460_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_198_)
  );
  NOT _461_ (
    .A(_198_),
    .Y(_199_)
  );
  NOR _462_ (
    .A(rd_ptr[0]),
    .B(_030_),
    .Y(_200_)
  );
  NOR _463_ (
    .A(_199_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _464_ (
    .A(rd_ptr[1]),
    .B(_201_),
    .Y(_202_)
  );
  NOR _465_ (
    .A(_197_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _466_ (
    .A(_163_),
    .B(_203_),
    .Y(_001_[3])
  );
  NOR _467_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_204_)
  );
  NAND _468_ (
    .A(_236_),
    .B(rd_ptr[0]),
    .Y(_205_)
  );
  NAND _469_ (
    .A(rd_ptr[1]),
    .B(_205_),
    .Y(_206_)
  );
  NOR _470_ (
    .A(_204_),
    .B(_206_),
    .Y(_207_)
  );
  NAND _471_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_208_)
  );
  NOT _472_ (
    .A(_208_),
    .Y(_209_)
  );
  NOR _473_ (
    .A(rd_ptr[0]),
    .B(_031_),
    .Y(_210_)
  );
  NOR _474_ (
    .A(_209_),
    .B(_210_),
    .Y(_211_)
  );
  NOR _475_ (
    .A(rd_ptr[1]),
    .B(_211_),
    .Y(_212_)
  );
  NOR _476_ (
    .A(_207_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _477_ (
    .A(_163_),
    .B(_213_),
    .Y(_001_[4])
  );
  NOR _478_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_214_)
  );
  NAND _479_ (
    .A(_237_),
    .B(rd_ptr[0]),
    .Y(_215_)
  );
  NAND _480_ (
    .A(rd_ptr[1]),
    .B(_215_),
    .Y(_216_)
  );
  NOR _481_ (
    .A(_214_),
    .B(_216_),
    .Y(_217_)
  );
  NAND _482_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_218_)
  );
  NOT _483_ (
    .A(_218_),
    .Y(_219_)
  );
  NOR _484_ (
    .A(rd_ptr[0]),
    .B(_032_),
    .Y(_220_)
  );
  NOR _485_ (
    .A(_219_),
    .B(_220_),
    .Y(_221_)
  );
  NOR _486_ (
    .A(rd_ptr[1]),
    .B(_221_),
    .Y(_222_)
  );
  NOR _487_ (
    .A(_217_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _488_ (
    .A(_163_),
    .B(_223_),
    .Y(_001_[5])
  );
  NOR _489_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_224_)
  );
  NAND _490_ (
    .A(reset),
    .B(_063_),
    .Y(_225_)
  );
  NOR _491_ (
    .A(_224_),
    .B(_225_),
    .Y(_003_[0])
  );
  NAND _492_ (
    .A(reset),
    .B(_065_),
    .Y(_226_)
  );
  NOR _493_ (
    .A(_115_),
    .B(_226_),
    .Y(_003_[1])
  );
  DFF _494_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _495_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _496_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _497_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _498_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _499_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _500_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _501_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _502_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _503_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _504_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _505_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _506_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _507_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _508_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _509_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _510_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _511_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _512_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _513_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _514_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _515_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _516_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _517_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _518_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _519_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "main_fifo_synth.v:59" *)
  DFF _520_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "main_fifo_synth.v:59" *)
  DFF _521_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "main_fifo_synth.v:59" *)
  DFF _522_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _523_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out[0])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _524_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out[1])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _525_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out[2])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _526_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out[3])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _527_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out[4])
  );
  (* src = "main_fifo_synth.v:44" *)
  DFF _528_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out[5])
  );
  (* src = "main_fifo_synth.v:31" *)
  DFF _529_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "main_fifo_synth.v:31" *)
  DFF _530_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
endmodule
