/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
module arbitro_enrutamiento_synth(VC0, VC1, clk, reset_L, VC0_empty, VC1_empty, D1_pause, D0_pause, VC1_pop_synth, VC0_pop_synth, D0_push, D1_push, arbitro_D0_out_synth, arbitro_D1_out_synth);
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC0_pop_synth;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC1_pop_synth;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] arbitro_D0_out_synth;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] arbitro_D1_out_synth;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:13" *)
  arbitro_mux_synth u_arbitro_mux_synthes (
    .D0_push(D0_push),
    .D1_push(D1_push),
    .VC0(VC0),
    .VC0_empty(VC0_empty),
    .VC1(VC1),
    .VC1_empty(VC1_empty),
    .arbitro_D0_out_synth(arbitro_D0_out_synth),
    .arbitro_D1_out_synth(arbitro_D1_out_synth),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:29" *)
  logica_pops_synth u_logica_pops_synth (
    .D0_pause(D0_pause),
    .D1_pause(D1_pause),
    .VC0_empty(VC0_empty),
    .VC0_pop_synth(VC0_pop_synth),
    .VC1_empty(VC1_empty),
    .VC1_pop_synth(VC1_pop_synth),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
module arbitro_mux_synth(reset_L, clk, VC0, VC1, pop_delay_VC0, pop_delay_VC1, VC0_empty, VC1_empty, arbitro_D0_out_synth, arbitro_D1_out_synth, D0_push, D1_push);
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire _000_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire _001_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _002_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:2" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:3" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] arbitro_D0_out_synth;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] arbitro_D1_out_synth;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input reset_L;
  NOT _059_ (
    .A(VC1[4]),
    .Y(_004_)
  );
  NOT _060_ (
    .A(VC0[4]),
    .Y(_005_)
  );
  NOT _061_ (
    .A(reset_L),
    .Y(_006_)
  );
  NOT _062_ (
    .A(VC1[0]),
    .Y(_007_)
  );
  NOT _063_ (
    .A(VC1[1]),
    .Y(_008_)
  );
  NOT _064_ (
    .A(VC1[2]),
    .Y(_009_)
  );
  NOT _065_ (
    .A(VC1[3]),
    .Y(_010_)
  );
  NOT _066_ (
    .A(VC1[5]),
    .Y(_011_)
  );
  NOT _067_ (
    .A(VC0[0]),
    .Y(_012_)
  );
  NOT _068_ (
    .A(VC0[1]),
    .Y(_013_)
  );
  NOT _069_ (
    .A(VC0[2]),
    .Y(_014_)
  );
  NOT _070_ (
    .A(VC0[3]),
    .Y(_015_)
  );
  NOT _071_ (
    .A(VC0[5]),
    .Y(_016_)
  );
  NOR _072_ (
    .A(VC0_empty),
    .B(VC0[4]),
    .Y(_017_)
  );
  NAND _073_ (
    .A(pop_delay_VC0),
    .B(_017_),
    .Y(_018_)
  );
  NAND _074_ (
    .A(pop_delay_VC1),
    .B(VC0_empty),
    .Y(_019_)
  );
  NOR _075_ (
    .A(VC1_empty),
    .B(_019_),
    .Y(_020_)
  );
  NAND _076_ (
    .A(_004_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _077_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _078_ (
    .A(reset_L),
    .B(_022_),
    .Y(_023_)
  );
  NOT _079_ (
    .A(_023_),
    .Y(_000_)
  );
  NOR _080_ (
    .A(VC0_empty),
    .B(_005_),
    .Y(_024_)
  );
  NAND _081_ (
    .A(pop_delay_VC0),
    .B(_024_),
    .Y(_025_)
  );
  NOR _082_ (
    .A(_012_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _083_ (
    .A(VC1[4]),
    .B(_020_),
    .Y(_027_)
  );
  NOR _084_ (
    .A(_007_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _085_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _086_ (
    .A(_006_),
    .B(_029_),
    .Y(_003_[0])
  );
  NOR _087_ (
    .A(_013_),
    .B(_025_),
    .Y(_030_)
  );
  NOR _088_ (
    .A(_008_),
    .B(_027_),
    .Y(_031_)
  );
  NOR _089_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _090_ (
    .A(_006_),
    .B(_032_),
    .Y(_003_[1])
  );
  NOR _091_ (
    .A(_014_),
    .B(_025_),
    .Y(_033_)
  );
  NOR _092_ (
    .A(_009_),
    .B(_027_),
    .Y(_034_)
  );
  NOR _093_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _094_ (
    .A(_006_),
    .B(_035_),
    .Y(_003_[2])
  );
  NOR _095_ (
    .A(_015_),
    .B(_025_),
    .Y(_036_)
  );
  NOR _096_ (
    .A(_010_),
    .B(_027_),
    .Y(_037_)
  );
  NOR _097_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _098_ (
    .A(_006_),
    .B(_038_),
    .Y(_003_[3])
  );
  NAND _099_ (
    .A(_025_),
    .B(_027_),
    .Y(_039_)
  );
  NAND _100_ (
    .A(reset_L),
    .B(_039_),
    .Y(_040_)
  );
  NOT _101_ (
    .A(_040_),
    .Y(_001_)
  );
  NOR _102_ (
    .A(_016_),
    .B(_025_),
    .Y(_041_)
  );
  NOR _103_ (
    .A(_011_),
    .B(_027_),
    .Y(_042_)
  );
  NOR _104_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _105_ (
    .A(_006_),
    .B(_043_),
    .Y(_003_[5])
  );
  NOR _106_ (
    .A(_012_),
    .B(_018_),
    .Y(_044_)
  );
  NOR _107_ (
    .A(_007_),
    .B(_021_),
    .Y(_045_)
  );
  NOR _108_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _109_ (
    .A(_006_),
    .B(_046_),
    .Y(_002_[0])
  );
  NOR _110_ (
    .A(_013_),
    .B(_018_),
    .Y(_047_)
  );
  NOR _111_ (
    .A(_008_),
    .B(_021_),
    .Y(_048_)
  );
  NOR _112_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _113_ (
    .A(_006_),
    .B(_049_),
    .Y(_002_[1])
  );
  NOR _114_ (
    .A(_014_),
    .B(_018_),
    .Y(_050_)
  );
  NOR _115_ (
    .A(_009_),
    .B(_021_),
    .Y(_051_)
  );
  NOR _116_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _117_ (
    .A(_006_),
    .B(_052_),
    .Y(_002_[2])
  );
  NOR _118_ (
    .A(_015_),
    .B(_018_),
    .Y(_053_)
  );
  NOR _119_ (
    .A(_010_),
    .B(_021_),
    .Y(_054_)
  );
  NOR _120_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _121_ (
    .A(_006_),
    .B(_055_),
    .Y(_002_[3])
  );
  NOR _122_ (
    .A(_016_),
    .B(_018_),
    .Y(_056_)
  );
  NOR _123_ (
    .A(_011_),
    .B(_021_),
    .Y(_057_)
  );
  NOR _124_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _125_ (
    .A(_006_),
    .B(_058_),
    .Y(_002_[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _126_ (
    .C(clk),
    .D(_002_[0]),
    .Q(arbitro_D0_out_synth[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _127_ (
    .C(clk),
    .D(_002_[1]),
    .Q(arbitro_D0_out_synth[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _128_ (
    .C(clk),
    .D(_002_[2]),
    .Q(arbitro_D0_out_synth[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _129_ (
    .C(clk),
    .D(_002_[3]),
    .Q(arbitro_D0_out_synth[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _130_ (
    .C(clk),
    .D(_002_[5]),
    .Q(arbitro_D0_out_synth[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _131_ (
    .C(clk),
    .D(_003_[0]),
    .Q(arbitro_D1_out_synth[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _132_ (
    .C(clk),
    .D(_003_[1]),
    .Q(arbitro_D1_out_synth[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _133_ (
    .C(clk),
    .D(_003_[2]),
    .Q(arbitro_D1_out_synth[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _134_ (
    .C(clk),
    .D(_003_[3]),
    .Q(arbitro_D1_out_synth[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _135_ (
    .C(clk),
    .D(_003_[5]),
    .Q(arbitro_D1_out_synth[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _136_ (
    .C(clk),
    .D(_000_),
    .Q(D0_push)
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _137_ (
    .C(clk),
    .D(_001_),
    .Q(D1_push)
  );
  assign _002_[4] = 1'h0;
  assign _003_[4] = _001_;
  assign arbitro_D0_out_synth[4] = 1'h0;
  assign arbitro_D1_out_synth[4] = D1_push;
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
module logica_pops_synth(VC0_empty, VC1_empty, D0_pause, D1_pause, clk, reset_L, VC0_pop_synth, VC1_pop_synth, pop_delay_VC0, pop_delay_VC1);
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  wire _00_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC0_pop_synth;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC1_pop_synth;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input reset_L;
  NOT _08_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOT _09_ (
    .A(VC1_empty),
    .Y(_03_)
  );
  NOT _10_ (
    .A(D1_pause),
    .Y(_04_)
  );
  NOR _11_ (
    .A(_02_),
    .B(D0_pause),
    .Y(_05_)
  );
  NAND _12_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _13_ (
    .A(VC0_empty),
    .B(_03_),
    .Y(_07_)
  );
  NOR _14_ (
    .A(_06_),
    .B(_07_),
    .Y(VC1_pop_synth)
  );
  NOR _15_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(VC0_pop_synth)
  );
  NOR _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_01_)
  );
  NOR _17_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(_00_)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _18_ (
    .C(clk),
    .D(_00_),
    .Q(pop_delay_VC0)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _19_ (
    .C(clk),
    .D(_01_),
    .Q(pop_delay_VC1)
  );
endmodule
